$ErrorActionPreference = "Stop"
$site = Split-Path -Parent $PSScriptRoot

function Html([string]$v) { [Net.WebUtility]::HtmlEncode($v) }
function J($v) { $v | ConvertTo-Json -Depth 12 -Compress }
function U([string]$v) { [Uri]::EscapeDataString($v) }

$products = @(
  [ordered]@{ id='tshirt'; slug='polo-yaka-is-tisortu'; name='Polo Yaka İş Tişörtü'; title='Polo Yaka İş Tişörtü Üreticisi | Kardeşler Tekstil'; meta='Polo yaka iş tişörtü üretimi: kurumsal renkte lakost ve penye seçenekleri, baskı, nakış ve özel model. Minimum 50 adet için teklif alın.'; image='tshirt/siyah-polo-yaka-tisort.webp'; fabric='Lakost, penye süprem ve ihtiyaca göre karışımlı örme kumaşlar'; stitch='Omuz, kol evi, yaka ve etek bölgelerinde kullanıma uygun dikiş planı'; durability='Sık kullanım ve kurumsal yıkama düzenine göre kumaş gramajı seçimi'; sectors='Fabrika, lojistik, market, restoran, otel ve saha servis ekipleri'; focus='gün boyu hareket eden ekiplerde nefes alma, düzgün yaka formu ve marka görünürlüğü'; logo='Göğüs ve kol bölgesinde nakış, DTF, transfer veya serigrafi'; intro='Polo yaka iş tişörtü, sahada rahatlık ile müşteri karşısında düzenli görünümü aynı üründe birleştirir. Kardeşler Tekstil, model kararını yalnız renge göre değil çalışma sıcaklığı, hareket yoğunluğu, vardiya süresi ve bakım sıklığına göre verir.'; detail='Lakost dokunun tok görünümü satış, servis ve yönetim ekiplerinde kurumsal bir siluet sağlar; penye süprem ise daha hafif görevlerde yumuşak temas ve hava geçirgenliği sunar. Yaka ribanası, pat genişliği ve düğme kalitesi tekrar kullanımda formun korunması açısından birlikte değerlendirilir.'; use='Fabrika içi hafif görevlerden lojistik depoya, mağaza personelinden restoran servisine kadar farklı bölümlere ayrı renk veya garni uygulanabilir. Kadın ve erkek kalıpları ile beden dağılımı numune aşamasında kontrol edildiğinde toplu siparişte çalışan kabulü yükselir.'; branding='Kurumsal logo için nakışın yoğunluğu, baskının esnekliği ve kumaşın ısıya tepkisi test edilir. Logo ölçüsü ve konumu onaylandıktan sonra model kodu, renk ve uygulama bilgisi kayıt altına alınır; böylece yeni çalışan ve tekrar sipariş ihtiyaçlarında aynı standarda dönülebilir.' },
  [ordered]@{ id='sweat'; slug='kurumsal-is-sweatshirtu'; name='Kurumsal İş Sweatshirtü'; title='Kurumsal İş Sweatshirtü ve Hoodie Üretimi'; meta='Kurumsal iş sweatshirtü ve hoodie üretimi: fermuarlı, kapüşonlu, polo veya bisiklet yaka modeller; logo baskı ve nakış seçenekleriyle teklif alın.'; image='sweat/siyah-polo-yaka-sweatshirt.webp'; fabric='İki iplik, üç iplik ve mevsime uygun örme kumaş seçenekleri'; stitch='Omuz, manşet, cep ve fermuar birleşimlerinde güçlendirilmiş uygulama'; durability='Vardiya, katmanlı kullanım ve tekrar yıkamaya uygun malzeme seçimi'; sectors='Depo, üretim, lojistik, teknik servis, market ve belediye ekipleri'; focus='serin iç ortam ve mevsim geçişlerinde hareket rahatlığıyla düzenli ekip görünümü'; logo='Göğüs, sırt ve kol için nakış veya kumaşa uygun baskı'; intro='Kurumsal iş sweatshirtü, tişört ile dış katman arasında çalışan pratik bir personel kıyafetidir. Isı değişiminin sık yaşandığı depo, üretim ve servis görevlerinde ürünün yalnız sıcak tutması değil, hareketi sınırlamaması ve vardiya boyunca formunu koruması gerekir.'; detail='İki iplik kumaş daha hafif geçiş dönemi kullanımı sunarken üç iplik seçenekler daha tok ve sıcak bir yapı sağlayabilir. Bisiklet yaka, polo yaka, yarım fermuar, tam fermuar ve kapüşon kararları görev alanındaki güvenlik, giyip çıkarma sıklığı ve kurumsal görünüm beklentisine göre alınır.'; use='Lojistik personelinde reflektif ayrıntılar, teknik ekiplerde fermuarlı cep, müşteri temaslı birimlerde ise sade renk blokları öne çıkabilir. Ribana, manşet ve etek yapısının ölçü dengesi; kol hareketi ve iç katmanla kullanım düşünülerek numunede incelenir.'; branding='Nakış uygulanacak bölgede kumaşın esnemesi ve destek malzemesi hesaba katılır. Baskı tercihinde yüzey, renk ve yıkama koşulu değerlendirilir. Onaylı logo yerleşimi kurumsal renk kodu ve ürün koduyla saklanarak farklı vardiyalar arasında görünüm birliği sağlanır.' },
  [ordered]@{ id='pantolon'; slug='is-pantolonu'; name='İş Pantolonu'; title='İş Pantolonu Üreticisi | Kargo Cepli ve Reflektörlü'; meta='İş pantolonu üretimi: gabardin, kargo cepli, diz takviyeli ve reflektörlü modeller. Kurumsal renk, özel cep ve logo seçenekleriyle teklif alın.'; image='pantolon/kt-pt-021-gri-diz-takviyeli-is-pantolonu.webp'; fabric='Gabardin, ripstop, denim ve göreve uygun karışımlı dokumalar'; stitch='Ağ, diz, cep ağzı ve kemer noktalarında güçlendirilmiş dikiş'; durability='Sürtünme, çömelme ve ekipman taşımaya göre takviye planı'; sectors='Fabrika, inşaat, lojistik, teknik bakım, belediye ve market ekipleri'; focus='hareket, cep erişimi ve aşınma dayanımını dengeli biçimde yönetmek'; logo='Cep kapağı veya uygun yüzeyde nakış, arma ve transfer'; intro='İş pantolonu, personelin hareketini ve günlük ekipman kullanımını doğrudan etkileyen temel iş kıyafetidir. Doğru model; yalnız kumaş kalınlığıyla değil, çalışanın çömelme, merdiven çıkma, araç kullanma ve gün boyunca taşıdığı araçlarla birlikte değerlendirilmelidir.'; detail='Gabardin tok görünüm ve geniş renk seçeneği sunarken ripstop yapı yırtılma ilerlemesini sınırlandırmaya yardımcı olabilir; denim belirli teknik ve servis görevlerinde farklı bir görünüm sağlar. Kumaş gramajı, esneklik ihtiyacı ve bakım talimatı gerçek çalışma koşuluna göre seçilir.'; use='Kargo cep, metre cebi, fermuarlı güvenli cep ve diz takviyesi her görev için aynı düzende kullanılmaz. Cep konumu oturma ve eğilme hareketinde rahatsızlık vermemeli; reflektif şerit gerekiyorsa görünürlük planına ve ürün tasarımına uyumlu yerleştirilmelidir.'; branding='Kurumsal renkler cep kapağı, biye veya kontrast panel üzerinden taşınabilir. Nakış ve arma için sürtünmesi düşük bir alan seçilir. Numunede bel yapısı, paça, diz hattı ve cep erişimi kontrol edilip teknik özellikler ürün koduyla sabitlenir.' },
  [ordered]@{ id='tulum'; slug='is-tulumu'; name='İş Tulumu'; title='İş Tulumu Üreticisi | Teknik ve Kurumsal Modeller'; meta='İş tulumu üretimi: bahçıvan ve tek parça modeller, çoklu cep, diz takviyesi, reflektör ve kurumsal logo seçenekleri. Toplu teklif alın.'; image='tulum/kt-tl-015-saks-mavi-bahcivan-tulumu.webp'; fabric='Göreve göre gabardin, karışımlı dokuma ve dayanıklı teknik kumaşlar'; stitch='Ağ, omuz, diz, fermuar ve cep bağlantılarında kontrollü dikiş'; durability='Bakım, üretim ve ağır saha hareketlerine göre takviye seçimi'; sectors='Üretim, otomotiv, bakım, tarım, inşaat, lojistik ve belediye'; focus='tek parça koruma, araç erişimi ve vardiya hareketini birlikte planlamak'; logo='Göğüs, sırt veya cep üstünde nakış, baskı ve arma'; intro='İş tulumu, üst ve alt bedeni tek çalışma setinde birleştirdiği için kalıp dengesi kritik bir üründür. Kardeşler Tekstil, bahçıvan ve tek parça tulum modellerini görev hareketi, kullanılan ekipman, çalışma sıcaklığı ve giyme-çıkarma düzenine göre planlar.'; detail='Kumaşın dayanımı kadar hava geçirgenliği ve bakım kolaylığı da önemlidir. Omuzdan ağa kadar ölçü dengesi yanlış olduğunda eğilme ve uzanma hareketleri zorlaşabilir. Fermuar, çıtçıt, askı tokası ve elastik bel gibi bileşenler vardiya şartına uygun kalite sınıfında seçilir.'; use='Bakım personelinde erişilebilir cepler, üretim hattında takılma riskini azaltan kapamalar, açık sahada reflektif ayrıntılar ve diz üstü görevlerde takviye panelleri gerekebilir. Bahçıvan tulumlarında askı ayarı ve göğüs cebi, farklı bedenlerin konforunu destekler.'; branding='Logo yerleşimi hareketli dikiş hatlarından uzak tutulur ve tek parça ürünün görünürlüğüne göre ölçeklendirilir. Nakış, transfer veya arma numunede kumaşla birlikte değerlendirilir; onay sonrası renk, aksesuar ve kalıp bilgileri tekrar üretim standardına bağlanır.' },
  [ordered]@{ id='onluk'; slug='asci-kiyafeti-is-onlugu'; name='Aşçı Kıyafeti ve İş Önlüğü'; title='Aşçı Kıyafeti ve İş Önlüğü Üreticisi'; meta='Aşçı kıyafeti ve iş önlüğü üretimi: mutfak, restoran, gıda, laboratuvar ve hizmet ekiplerine özel kumaş, cep, baskı ve nakış seçenekleri.'; image='onluk/01.webp'; fabric='Kolay bakımlı dokuma, poplin ve kullanım alanına uygun karışımlar'; stitch='Cep, kol ağzı, ön kapama ve yan yırtmaçlarda düzenli dikiş'; durability='Sık yıkama, leke yönetimi ve yoğun servis temposuna uygun seçim'; sectors='Restoran, otel, kafe, gıda üretimi, sağlık, laboratuvar ve eğitim'; focus='hijyen algısı, görev ayrımı ve müşteri karşısındaki kurumsal görünüm'; logo='Göğüs, kol veya önlük yüzeyinde nakış ve uygun baskı'; intro='Aşçı kıyafeti ve iş önlüğü, hijyen gerektiren üretim ile müşteri temaslı hizmet alanlarında ekibin görevini görünür kılar. Mutfak sıcaklığı, leke türü, yıkama sıklığı ve personelin yaptığı hareketler model seçiminde birlikte ele alınmalıdır.'; detail='Aşçı ceketi için kapama düzeni, kol boyu, yaka formu ve hava dolaşımı; önlükte ise boy, bağlama noktası ve cep konumu kullanım konforunu belirler. Poplin ve karışımlı dokumalar arasında karar verilirken tok görünüm, kırışma davranışı ve bakım süreci karşılaştırılır.'; use='Restoran mutfağı, otel kat hizmetleri, gıda üretim alanı, laboratuvar ve danışma görevi aynı önlük yapısını gerektirmez. Renk ve model departman ayrımını destekleyebilir; hareketli görevlerde yan yırtmaç ve doğru etek boyu gün boyu rahatlık sağlar.'; branding='Kurumsal logo, sıcak yüzey ve sık yıkama koşulu dikkate alınarak nakış ya da baskıyla uygulanır. İnce çizgili logolarda okunabilirlik, nakışta arka destek ve ten temasında konfor kontrol edilir. Onaylı model, renk ve logo dosyası sonraki şube siparişleri için saklanır.' },
  [ordered]@{ id='montkaban'; slug='is-montu-kaban'; name='İş Montu ve Kaban'; title='İş Montu ve Kaban Üreticisi | Kışlık İş Kıyafeti'; meta='İş montu ve kaban üretimi: dolgulu, kapüşonlu, reflektörlü ve kurumsal logolu kışlık modeller. Saha ekipleri için toplu teklif alın.'; image='montkaban/01.webp'; fabric='Dış yüzey, astar ve dolgu katmanı görev koşuluna göre seçilir'; stitch='Omuz, kol, cep, fermuar ve astar birleşimlerinde dayanıklı yapı'; durability='Soğuk, rüzgâr, hafif yağış ve saha sürtünmesine göre planlama'; sectors='İnşaat, güvenlik, lojistik, belediye, teknik servis ve açık saha'; focus='soğuk hava korumasını hareket, görünürlük ve katmanlama ile dengelemek'; logo='Göğüs, kol veya sırtta nakış, arma ve uygun transfer'; intro='İş montu ve kaban, açık saha personelinin hava koşullarına karşı kullandığı ana dış katmandır. Ürünün sıcaklık sağlaması kadar iç katmanlarla uyumu, kol hareketini koruması ve araç kullanımında gereksiz hacim oluşturmaması önemlidir.'; detail='Dış kumaşın rüzgâr ve hafif yağış davranışı, dolgunun kalınlığı, astarın sürtünme direnci ve fermuar kalitesi tek sistem olarak değerlendirilir. Kapüşonun sabit ya da çıkarılabilir olması, manşet ayarı ve etek kapaması çalışma alanındaki güvenlik gereksinimine göre seçilir.'; use='Güvenlik ve belediye ekiplerinde gece görünürlüğü, lojistikte araç giriş çıkışı, inşaatta açık alan dayanımı, teknik serviste ise cep erişimi öne çıkar. Reflektif ayrıntılar görünürlük ihtiyacına göre yerleştirilir; koruyucu sertifika iddiası gerekiyorsa ayrıca teknik doğrulama istenir.'; branding='Kalın dış katmanda nakış yapılırken su itici yüzey, astar ve dolgu etkisi hesaba katılır. Alternatif olarak arma veya uygun transfer değerlendirilebilir. Numunede logo konumu, fermuar çalışması ve beden payı kontrol edilerek kurumsal model standardı oluşturulur.' },
  [ordered]@{ id='polar'; slug='polar-is-montu'; name='Polar İş Montu'; title='Polar İş Montu Üreticisi | Kurumsal Polar'; meta='Polar iş montu üretimi: fermuarlı, cepli, garnili ve logolu kurumsal polar modelleri. Depo, servis ve saha ekipleri için toplu teklif alın.'; image='polar/kt-pl-015-antrasit-omuz-garnili-polar-mont.webp'; fabric='Farklı gramajlarda polar ve ihtiyaca göre takviyeli yüzeyler'; stitch='Fermuar, cep, yaka ve omuz birleşimlerinde dengeli dikiş'; durability='Tüylenme, form koruma ve katmanlı kullanıma göre kumaş seçimi'; sectors='Depo, lojistik, servis, güvenlik, market, otel ve belediye'; focus='hafif sıcaklık, hızlı giyip çıkarma ve rahat ara katman kullanımı'; logo='Göğüs veya kol bölgesinde kontrollü nakış ve arma'; intro='Polar iş montu, serin depo ve atölyeler ile mevsim geçişindeki saha görevlerinde hafif bir ara katman sunar. Yumuşak tutum tek başına yeterli değildir; kumaş gramajı, tüylenme davranışı, fermuar kalitesi ve dış katman altında oluşturduğu hacim birlikte değerlendirilmelidir.'; detail='Tam fermuarlı modeller sıcaklık değişiminde pratik kullanım sağlarken yarım fermuar seçenekleri farklı bir gövde dengesi sunar. Dik yaka, cep sayısı, elastik etek ve omuz garnisi göreve göre belirlenir. Sürtünmenin yoğun olduğu bölgelerde dokuma takviye parçaları tercih edilebilir.'; use='Depo ve lojistikte hareket rahatlığı, güvenlikte uzun vardiya konforu, otel teknik servisinde temiz görünüm, saha ekiplerinde ise mont altına uyum önem kazanır. Beden payı hem tek başına hem tişört veya sweatshirt üzerinde denenerek belirlenir.'; branding='Polar yüzey nakış sırasında esneyebileceği için uygun destek ve dikiş yoğunluğu kullanılır. Çok küçük yazılar ile aşırı yoğun logolar yüzeyde bozulma yaratabileceğinden numune üzerinde okunabilirlik kontrol edilir. Renk, garni ve logo standardı ürün koduyla kaydedilir.' },
  [ordered]@{ id='yelek'; slug='reflektorlu-is-yelegi'; name='Reflektörlü İş Yeleği'; title='Reflektörlü İş Yeleği Üreticisi | Kurumsal Yelek'; meta='Reflektörlü iş yeleği üretimi: ikaz, çok cepli, polar, softshell ve dolgulu modeller; kurumsal renk ve logo uygulamasıyla toplu teklif alın.'; image='yelek/kt-yl-014-siyah-softshell-is-yelegi.webp'; fabric='İkazlık, dokuma, softshell, polar veya dolgulu modele uygun malzeme'; stitch='Cep, omuz, fermuar ve reflektif bant bağlantılarında sağlam uygulama'; durability='Araç trafiği, ekipman taşıma ve sık giyip çıkarmaya göre tasarım'; sectors='Lojistik, inşaat, fabrika, güvenlik, belediye, market ve servis'; focus='görünürlük, cep düzeni ve katmansız hareket özgürlüğünü bir araya getirmek'; logo='Göğüs ve sırtta baskı, transfer, nakış veya arma'; intro='Reflektörlü iş yeleği, personelin hareketini sınırlamadan görünürlüğü ve görev tanımını destekleyen tamamlayıcı üründür. İkaz yeleği, çok cepli saha yeleği, softshell ya da dolgulu model seçenekleri aynı ihtiyaca cevap vermez; çalışma ortamı doğru tanımlanmalıdır.'; detail='Yüksek görünürlük gereken alanlarda zemin rengi, reflektif bant genişliği ve yerleşimi risk değerlendirmesiyle ele alınır. Çok cepli modellerde yük dağılımı, fermuar erişimi ve ekipmanın düşmesini önleyen kapamalar önemlidir. Polar ve dolgulu yeleklerde sıcaklık ile hareket dengesi ayrıca incelenir.'; use='Lojistik sahasında araç trafiği, inşaatta açık alan, fabrikada bölüm tanımı, markette hızlı görev geçişi ve güvenlikte uzun vardiya farklı yelek düzenleri gerektirir. Ürün bir kişisel koruyucu donanım standardını karşılayacaksa ilgili belge ve sınıf ayrıca doğrulanmalıdır.'; branding='Logo baskısı reflektif alanı kapatmayacak ve görünürlük dengesini bozmayacak konuma yerleştirilir. Kalın yeleklerde nakış, ince ikazlık kumaşta transfer veya baskı değerlendirilebilir. Numune onayıyla renk, bant ve logo yerleşimi tekrar sipariş için sabitlenir.' },
  [ordered]@{ id='softshell'; slug='softshell-is-montu'; name='Softshell İş Montu'; title='Softshell İş Montu Üreticisi | Kurumsal Softshell'; meta='Softshell iş montu üretimi: esnek, su itici, nefes alabilen, reflektörlü ve logolu modeller. Saha ve servis ekipleri için toplu teklif alın.'; image='softshell/kt-ss-015-antrasit-kapusonlu-softshell-mont.webp'; fabric='Esnek dokuma dış yüzey ve modele göre iç katmanlı softshell'; stitch='Fermuar, cep, kol ve panel birleşimlerinde hareket odaklı dikiş'; durability='Rüzgâr, hafif yağış, sürtünme ve sık saha kullanımına göre seçim'; sectors='Teknik servis, lojistik, güvenlik, inşaat, belediye ve satış ekipleri'; focus='hava koşullarına uyumu modern kurumsal görünüm ve esneklikle birleştirmek'; logo='Göğüs, kol ve sırtta nakış, arma veya yüzeye uygun transfer'; intro='Softshell iş montu, mevsim geçişlerinde dış ortam ile kapalı alan arasında hareket eden personel için dengeli bir katmandır. Esnek yapı, rüzgâr direnci ve su itici yüzey pratik avantaj sağlayabilir; ancak ürünün performansı kumaş yapısı, dikişler ve bakım koşuluyla birlikte değerlendirilmelidir.'; detail='Farklı softshell yapıları aynı nefes alma veya su dayanımı değerini sunmaz. Bu nedenle görev süresi, yağış maruziyeti, fiziksel hareket ve iç katman belirlenmeden yalnız ürün adına göre seçim yapılmaz. Fermuarlı cepler, kapüşon, manşet ve etek ayarı gerçek kullanım senaryosuna göre düzenlenir.'; use='Teknik servis çalışanında temiz siluet ve cep erişimi, lojistikte hareket ile araç trafiği, güvenlikte uzun vardiya, belediye ekibinde ise dış hava değişimi öne çıkar. Reflektif panel gerekiyorsa tasarıma eklenir; özel koruma beklentileri teknik belgeyle ayrıca tanımlanır.'; branding='Softshell yüzeye logo uygulanırken membran veya kaplama yapısının iğne ve ısıyla etkileşimi incelenir. Nakış, arma ya da transfer arasındaki karar numune üzerinde verilir. Kurumsal renk, fermuar ve logo ölçüsü kaydedilerek sonraki alımlarda görünüm tutarlılığı korunur.' },
  [ordered]@{ id='isg'; slug='is-guvenligi-ekipmanlari'; name='İş Güvenliği Ekipmanları'; title='İş Güvenliği Ekipmanları ve İkaz Yelekleri'; meta='İş güvenliği ekipmanları: ikaz yeleği, reflektörlü yelek, iş ayakkabısı ve baret seçeneklerini kurumsal kıyafet projenizle birlikte planlayın.'; image='isg/1.webp'; fabric='İkaz yeleklerinde görünür zemin ve uygun reflektif bileşenler'; stitch='Bant, kenar, kapama ve logo bölgelerinde ürüne uygun uygulama'; durability='Saha riski, kullanım sıklığı ve bakım koşuluna göre ürün seçimi'; sectors='İnşaat, fabrika, lojistik, belediye, güvenlik ve teknik bakım'; focus='iş kıyafeti setini görünürlük, ayak ve baş koruma ihtiyaçlarıyla tamamlamak'; logo='İkaz yeleğinde görünürlüğü engellemeyen baskı veya transfer'; intro='İş güvenliği ekipmanları, kurumsal iş kıyafetinden farklı olarak risk değerlendirmesi ve görev gereksinimiyle seçilmelidir. İkaz yeleği, iş ayakkabısı ve baret aynı ürün grubunda sunulsa da her biri farklı tehlikeye cevap verir; yalnız görsel uyum koruma yeterliliğinin yerine geçmez.'; detail='Reflektörlü ikaz yeleğinde zemin rengi ve bant düzeni, iş ayakkabısında burun koruması, taban ve kayma davranışı, barette ise kullanım sınıfı ve uyumlu aksesuarlar incelenir. İstenen standart veya koruma seviyesi satın alma şartnamesinde açıkça belirtilmeli ve belgeyle doğrulanmalıdır.'; use='İnşaat sahası, fabrika üretim hattı, lojistik merkezi ve belediye operasyonu farklı riskler taşır. Ürün seçimi iş güvenliği uzmanının değerlendirmesi, çalışan görevi, ortam ve diğer donanımlarla uyum üzerinden yapılmalıdır. Beden ve ayar seçenekleri de düzenli kullanımın sürdürülebilmesi için önemlidir.'; branding='Kurumsal logo ikaz yeleğinde reflektif alanı ve görünür zemini gereksiz yere kapatmamalıdır. Baskı konumu numunede değerlendirilir. Kask veya ayakkabı üzerindeki markalama ise üretici talimatı ve ürün uygunluğu çerçevesinde ele alınır; koruyucu yapıyı değiştirecek işlem yapılmaz.' },
  [ordered]@{ id='promosyon'; slug='kurumsal-promosyon-urunleri'; name='Kurumsal Promosyon Ürünleri'; title='Kurumsal Promosyon Ürünleri | Logolu Tekstil'; meta='Kurumsal promosyon ürünleri: logolu bere, şapka, polar atkı ve tekstil aksesuarları. Marka rengi, nakış ve toplu üretim seçenekleri için teklif alın.'; image='promosyon/promosyon-triko-bere.webp'; fabric='Polar, triko ve ürüne göre kurumsal kullanıma uygun tekstil yüzeyleri'; stitch='Kenar, birleşim ve logo bölgesinde ürüne uygun temiz işçilik'; durability='Etkinlik, saha dağıtımı ve tekrar kullanım senaryosuna göre seçim'; sectors='Fabrika, eğitim, otel, restoran, market, belediye ve etkinlik ekipleri'; focus='marka hatırlanırlığını işlevsel ve kullanılabilir tekstil ürünleriyle desteklemek'; logo='Nakış, arma, transfer veya ürüne uygun baskı'; intro='Kurumsal promosyon ürünleri, yalnız dağıtılan bir hediye değil markayla tekrar temas sağlayan işlevsel bir iletişim aracıdır. Bere, şapka, polar atkı ve benzeri tekstil aksesuarları hedef kullanıcı, mevsim, dağıtım ortamı ve beklenen kullanım süresine göre seçildiğinde daha anlamlı sonuç verir.'; detail='Triko ürünlerde örgü yapısı ve esneklik, polar aksesuarlarda gramaj ile kenar temizliği, şapkalarda panel ve ayar mekanizması önemlidir. Kurumsal renk ekranda görülen tonla gerçek malzemede farklılaşabileceğinden kartela ve numune üzerinden kontrol edilmesi gerekir.'; use='Çalışan kiti, bayi toplantısı, fuar, saha etkinliği veya müşteri hediyesi farklı ürün ve paketleme kararları doğurur. Kullanıcının günlük hayatta değerlendirebileceği sade tasarım marka görünürlüğünü uzatırken gereksiz büyük logo ürünün kullanım isteğini azaltabilir.'; branding='Nakışın dikiş yoğunluğu esnek yüzeyde formu bozmamalı; baskı ise malzeme ve bakım koşuluna uygun olmalıdır. Logo dosyası, renk kodu, uygulama ölçüsü ve konumu numunede onaylanır. Çoklu ürün setlerinde aynı marka dili ambalaj ve etiketlemeye de taşınabilir.' }
)

$sectors = @('Fabrika','İnşaat','Sağlık','Otel','Restoran','Lojistik','Market','Belediye')
$locations = @(
  @{slug='istanbul-is-elbiseleri';name='İstanbul İş Elbiseleri'},
  @{slug='anadolu-yakasi-is-elbiseleri';name='Anadolu Yakası İş Elbiseleri'},
  @{slug='pendik-is-elbiseleri';name='Pendik İş Elbiseleri'},
  @{slug='tuzla-is-elbiseleri';name='Tuzla İş Elbiseleri'}
)

foreach ($p in $products) {
  $url = "https://kardeslertekstil.com.tr/$($p.slug)/"
  $image = "https://kardeslertekstil.com.tr/assets/products/gallery/$($p.image)"
  $faqs = @(
    @{q="$($p.name) için minimum sipariş kaç adettir?";a="Özel üretimde minimum sipariş 50 adettir. Model, kumaş, renk, beden dağılımı ve logo uygulaması toplam proje kapsamında değerlendirilir."},
    @{q="$($p.name) üzerine logo uygulanabilir mi?";a="$($p.logo). Uygulama yöntemi logo ayrıntısı, kumaş yüzeyi, renk ve bakım koşuluna göre numune aşamasında belirlenir."},
    @{q="$($p.name) kumaşı nasıl seçilir?";a="$($p.fabric). Kesin seçim çalışma ortamı, kullanım süresi, hareket yoğunluğu ve bakım düzeni görüldükten sonra yapılır."},
    @{q="$($p.name) için numune hazırlanıyor mu?";a="Proje kapsamına göre numune planlanabilir. Numunede kalıp, beden, hareket, kumaş, aksesuar ve logo yerleşimi kontrol edilerek seri üretim ayrıntıları yazılı onaya bağlanır."},
    @{q="$($p.name) renkleri kurumsal kimliğe göre üretilebilir mi?";a="Kumaş ve aksesuar seçenekleri elverdiğinde kurum renkleri ana yüzey, garni, biye veya tamamlayıcı parçalarda uygulanabilir. Ton kararı fiziksel kartela ya da numune üzerinden doğrulanır."},
    @{q="$($p.name) siparişinde teklif için hangi bilgiler gerekir?";a="Yaklaşık adet, görev ve sektör, beden dağılımı, tercih edilen model, renk, logo dosyası, teslimat şehri ve hedef tarih paylaşılırsa yazılı teklif kapsamı daha doğru hazırlanabilir."}
  )
  $productSchema = [ordered]@{'@context'='https://schema.org';'@type'='Product';name=$p.name;description=$p.meta;url=$url;image=@($image);sku="KT-$($p.id.ToUpper())-KATEGORI";category='Kurumsal iş kıyafeti';brand=@{'@type'='Brand';name='Kardeşler Tekstil'};manufacturer=@{'@type'='Organization';name='Kardeşler Tekstil';'@id'='https://kardeslertekstil.com.tr/#organization'};additionalProperty=@(@{'@type'='PropertyValue';name='Minimum sipariş';value='50 adet'},@{'@type'='PropertyValue';name='Üretim türü';value='Sipariş üzerine kurumsal üretim'},@{'@type'='PropertyValue';name='Logo uygulaması';value=$p.logo})}
  $breadcrumb = [ordered]@{'@context'='https://schema.org';'@type'='BreadcrumbList';itemListElement=@(@{'@type'='ListItem';position=1;name='Ana Sayfa';item='https://kardeslertekstil.com.tr/'},@{'@type'='ListItem';position=2;name='Ürünlerimiz';item='https://kardeslertekstil.com.tr/urunlerimiz'},@{'@type'='ListItem';position=3;name=$p.name;item=$url})}
  $faqSchema = [ordered]@{'@context'='https://schema.org';'@type'='FAQPage';mainEntity=@($faqs | ForEach-Object { @{'@type'='Question';name=$_.q;acceptedAnswer=@{'@type'='Answer';text=$_.a}} })}
  $faqHtml = ($faqs | ForEach-Object { "<details><summary>$(Html $_.q)</summary><p>$(Html $_.a)</p></details>" }) -join ''
  $featureHtml = @(
    @('Kumaş',$p.fabric),@('Dikiş',$p.stitch),@('Dayanıklılık',$p.durability),@('Nakış',$p.logo),@('Baskı','Logo ve kumaş yüzeyine göre DTF, transfer veya serigrafi değerlendirmesi'),@('Renk seçenekleri','Kurumsal kartela, garni ve aksesuarlarla proje bazlı renk planı')
  ) | ForEach-Object { "<article><h3>$(Html $_[0])</h3><p>$(Html $_[1])</p></article>" }
  $sectorHtml = ($sectors | ForEach-Object { "<li>$(Html $_)</li>" }) -join ''
  $related = @($products | Where-Object {$_.slug -ne $p.slug} | Select-Object -First 4)
  $relatedHtml = ($related | ForEach-Object { "<a class=`"local-product-card`" href=`"../$($_.slug)/`"><h3>$(Html $_.name)</h3><p>Kurumsal üretim, kumaş ve logo seçeneklerini inceleyin.</p><strong>Ürün sayfasına gidin →</strong></a>" }) -join ''
  $locationHtml = ($locations | ForEach-Object { "<a href=`"../$($_.slug)/`">$(Html $_.name)</a>" }) -join ''
  $waText = U "Merhaba, $($p.name) için kurumsal teklif almak istiyorum."
  $formProduct = U $p.name
  $formMessage = U "$($p.name) için adet, beden, logo ve teslimat bilgilerini içeren yazılı teklif almak istiyorum."
  $html = @"
<!doctype html><html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>$(Html $p.title)</title><meta name="description" content="$(Html $p.meta)"><meta name="robots" content="index,follow,max-image-preview:large"><link rel="canonical" href="$url"><link rel="stylesheet" href="../styles.css?v=20260803-2">
<meta property="og:type" content="product"><meta property="og:locale" content="tr_TR"><meta property="og:site_name" content="Kardeşler Tekstil"><meta property="og:title" content="$(Html $p.title)"><meta property="og:description" content="$(Html $p.meta)"><meta property="og:url" content="$url"><meta property="og:image" content="$image"><meta property="og:image:alt" content="$(Html $p.name) kurumsal üretim modeli">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="$(Html $p.title)"><meta name="twitter:description" content="$(Html $p.meta)"><meta name="twitter:image" content="$image"><meta name="twitter:image:alt" content="$(Html $p.name) kurumsal üretim modeli">
<script type="application/ld+json">$(J $productSchema)</script><script type="application/ld+json">$(J $breadcrumb)</script><script type="application/ld+json">$(J $faqSchema)</script>
<link rel="icon" type="image/svg+xml" href="/favicon.svg?v=9"><link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png?v=9"><link rel="shortcut icon" href="/favicon.ico?v=9"><link rel="apple-touch-icon" href="/apple-touch-icon.png?v=9"><meta name="theme-color" content="#f97316"><meta name="google-analytics-id" content=""><script src="/site.js?v=20260802-2" defer></script></head>
<body class="local-page product-seo-page"><header class="site-header"><div class="container"><a class="brand" href="../"><img src="../assets/logo-kit-badge.webp" alt="Kardeşler Tekstil"></a><nav class="nav" aria-label="Ana navigasyon"><a href="../">Ana Sayfa</a><a class="active" href="../urunlerimiz">Ürünlerimiz</a><a href="../referanslarimiz">Referanslarımız</a><a href="../hakkimizda">Hakkımızda</a><a href="../bilgi-merkezi/">Bilgi Merkezi</a><a href="../iletisim">İletişim</a></nav><a class="btn btn-accent" href="https://wa.me/902163961988" target="_blank" rel="noopener">Teklif Al</a></div></header>
<main><section class="page-head product-seo-hero"><div class="container product-seo-hero-grid"><div><div class="eyebrow eyebrow-accent">KURUMSAL ÜRÜN ÇÖZÜMÜ</div><h1>$(Html $p.name)</h1><p>$(Html $p.meta)</p><div class="cta-row"><a class="btn btn-whatsapp" href="https://wa.me/902163961988?text=$waText" target="_blank" rel="noopener">WhatsApp ile Görüşün</a><a class="btn btn-quote-form" href="../iletisim?urun=$formProduct&amp;mesaj=$formMessage#teklif-formu">Teklif İsteyin</a></div></div><figure><img src="../assets/products/gallery/$($p.image)" alt="$(Html $p.name) örnek kurumsal üretim modeli" width="640" height="640"></figure></div></section>
<section class="local-section"><div class="container product-seo-copy"><div><div class="eyebrow eyebrow-accent">ÜRÜN AÇIKLAMASI</div><h2>$(Html $p.name) üretiminde doğru teknik plan</h2><p>$(Html $p.intro)</p><p>$(Html $p.detail)</p><p>$(Html $p.use)</p><p>$(Html $p.branding)</p><p>$(Html "$($p.name) satın alımında teknik şartname hazırlanırken şu malzeme çerçevesi açıkça yazılmalıdır: $($p.fabric). Bunun yanında $($p.stitch.ToLower()) ölçülebilir bir kabul noktası olarak numunede incelenir. Beden dağılımı yalnız çalışan sayısından çıkarılmaz; görevin hareket biçimi, ürünün alt veya üst katmanla giyilmesi ve vardiya boyunca ihtiyaç duyulan rahatlık da hesaba katılır. İlk siparişte onaylanan fiziksel numunenin ürün kodu, kumaş referansı, renk tonu ve aksesuar bilgileriyle saklanması; sonraki alımlarda farklı yorumların önüne geçer ve şubeler arasında ortak bir kıyafet standardı kurulmasını kolaylaştırır.")</p><p>$(Html "$($p.sectors) için hazırlanan $($p.name.ToLower()) projelerinde kalite kontrol yalnız son görünüşe bırakılmaz. $($p.durability.ToLower()) üretim öncesi kararın merkezindedir; kesim ölçüsü, kritik dikişler, logo konumu ve paket içeriği aşamalı olarak takip edilir. Satın alma ekibi adet, çalışan görevleri, teslimat noktaları ve hedef tarihi teklif formunda paylaştığında gereksiz özellikler ayrıştırılabilir, gerekli işlevler ise yazılı kapsama alınabilir. Böylece tekliflerin aynı teknik temel üzerinden karşılaştırılması, beden değişimlerinin yönetilmesi ve yeni personel için devam siparişinin doğru modelden açılması mümkün olur. Üretim çözümü, yalnız ilk teslimatı değil ürünün kurum içindeki kullanım ve yenileme düzenini de destekleyecek biçimde planlanır.")</p></div><aside class="local-service-note"><strong>Kurumsal üretim</strong><p>$(Html $p.focus).</p><span>Minimum 50 adet · Numune planı · Logo uygulaması</span></aside></div></section>
<section class="local-section local-section-muted"><div class="container"><div class="section-head"><div><div class="eyebrow eyebrow-accent">TEKNİK ÖZELLİKLER</div><h2>Malzeme ve uygulama seçenekleri</h2></div><p>Kesin teknik özellikler kullanım alanı, adet ve onaylanan numuneye göre belirlenir.</p></div><div class="local-benefit-grid">$($featureHtml -join '')</div></div></section>
<section class="local-section"><div class="container product-seo-sector-layout"><div><div class="eyebrow eyebrow-accent">KULLANIM ALANLARI</div><h2>Hangi sektörler kullanıyor?</h2><p>$(Html $p.sectors). Her sektörün hareket, bakım, görünürlük ve kurumsal temsil beklentisi ayrı değerlendirilir.</p></div><ul>$sectorHtml</ul></div></section>
<section class="local-section local-section-dark"><div class="container"><div class="section-head"><div><div class="eyebrow eyebrow-accent">ÜRETİM SÜRECİ</div><h2>İhtiyaçtan kontrollü teslimata</h2></div><p>Ürün standardı yazılı bilgi ve numune kararıyla oluşturulur.</p></div><ol class="product-seo-process"><li><strong>İhtiyaç analizi</strong><span>Görev, ortam, adet, beden ve hedef tarih alınır.</span></li><li><strong>Teknik seçim</strong><span>Kumaş, kalıp, renk, aksesuar ve logo yöntemi belirlenir.</span></li><li><strong>Numune ve onay</strong><span>Hareket, ölçü, görünüm ve uygulamalar kontrol edilir.</span></li><li><strong>Üretim ve teslimat</strong><span>Onaylı standarda göre üretim, kalite kontrol ve paketleme yapılır.</span></li></ol></div></section>
<section class="local-section"><div class="container local-faq"><div class="section-head"><div><div class="eyebrow eyebrow-accent">SIK SORULAN SORULAR</div><h2>$(Html $p.name) hakkında</h2></div><p>Toplu satın alma öncesinde üretim, adet, kumaş ve logo kararları.</p></div>$faqHtml</div></section>
<section class="local-section local-section-muted"><div class="container"><div class="section-head"><div><div class="eyebrow eyebrow-accent">BENZER ÜRÜNLER</div><h2>Kurumsal ürün setini tamamlayın</h2></div><p>Birlikte kullanılan ürün gruplarını aynı renk ve logo standardında planlayın.</p></div><div class="local-product-grid">$relatedHtml</div></div></section>
<section class="local-section"><div class="container product-seo-links"><div><div class="eyebrow eyebrow-accent">HİZMET BÖLGELERİ</div><h2>İstanbul ve Anadolu Yakası üretim çözümleri</h2><p>Lokasyon bazlı planlama, teslimat ve kurumsal iş kıyafeti yaklaşımımızı inceleyin.</p></div><nav aria-label="Ürün hizmet bölgeleri">$locationHtml</nav></div></section>
<section class="local-final-cta"><div class="container"><div><div class="eyebrow eyebrow-accent">KURUMSAL TEKLİF</div><h2>$(Html $p.name) projenizi birlikte planlayalım.</h2><p>Adet, beden dağılımı, logo dosyası ve teslimat hedefinizi paylaşın; yazılı üretim kapsamını oluşturalım.</p></div><div class="local-cta-actions"><a class="btn btn-whatsapp" href="https://wa.me/902163961988?text=$waText" target="_blank" rel="noopener">WhatsApp</a><a class="btn btn-quote-form" href="../iletisim?urun=$formProduct&amp;mesaj=$formMessage#teklif-formu">Teklif Formu</a><a class="btn btn-secondary-dark" href="mailto:kardesler@kardeslertekstil.com.tr?subject=$(U "$($p.name) Kurumsal Teklif Talebi")">E-posta</a></div></div></section></main>
<footer class="site-footer"><div class="container grid"><div><img class="footer-logo" src="../assets/logo-kit-badge.webp" alt="Kardeşler Tekstil"><p class="tagline">1982'den bu yana kurumsal firmalara özel iş kıyafeti üretiyoruz.</p></div><div><h4>Site</h4><a href="../">Ana Sayfa</a><a href="../urunlerimiz">Ürünlerimiz</a><a href="../referanslarimiz">Referanslarımız</a><a href="../hakkimizda">Hakkımızda</a><a href="../bilgi-merkezi/">Bilgi Merkezi</a></div><div><h4>İletişim</h4><div class="ico-row">Fevzi Çakmak, Ulukapı Sk. 11-12/A, Pendik / İstanbul</div><div class="ico-row"><a href="tel:+902163961988">0216 396 19 88</a></div><div class="ico-row"><a href="mailto:kardesler@kardeslertekstil.com.tr">kardesler@kardeslertekstil.com.tr</a></div></div><div><h4>Hızlı Teklif</h4><a class="btn btn-whatsapp" href="https://wa.me/902163961988" target="_blank" rel="noopener">WhatsApp'tan Teklif Al</a></div></div><div class="bottom"><span>© 2026 Kardeşler Tekstil A.Ş.</span><span>EST. 1982 · Pendik / İstanbul</span></div></footer></body></html>
"@
  $dir = Join-Path $site $p.slug
  New-Item -ItemType Directory -Force -Path $dir | Out-Null
  [IO.File]::WriteAllText((Join-Path $dir 'index.html'), $html, (New-Object Text.UTF8Encoding($false)))
}

Write-Output "Generated $($products.Count) product SEO pages."
