$ErrorActionPreference = "Stop"
Remove-Item Alias:H -ErrorAction SilentlyContinue
$siteRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$utf8 = New-Object System.Text.UTF8Encoding($false)

# Windows PowerShell 5.1 reads UTF-8 scripts correctly only when they carry a BOM.
# Fail closed instead of publishing mojibake if that marker is ever removed.
if ([int][char]'İ' -ne 304 -or [int][char]'ş' -ne 351) {
  throw "Bu dosya UTF-8 olarak okunamadı. Bölgesel sayfalar oluşturulmadı."
}

$locations = @(
  [ordered]@{ slug="pendik-is-elbiseleri"; place="Pendik"; target="Pendik iş elbiseleri"; title="Pendik İş Elbiseleri ve Personel Kıyafetleri"; meta="Pendik iş elbiseleri ve personel kıyafetleri için doğrudan üretim, logo baskı, nakış ve numune desteği. Minimum 50 adet kurumsal teklif alın."; hero="Pendik İş Elbiseleri ve Personel Kıyafetleri Üreticisi"; lead="Pendik'teki üretim tesisimizden ilçedeki fabrikalara, lojistik ekiplerine, teknik servislere ve hizmet işletmelerine özel iş elbiseleri ve personel kıyafetleri hazırlıyoruz."; areas="Fevzi Çakmak, Kaynarca, Kurtköy, Şeyhli, Güzelyalı ve çevresi"; profile="Pendik; sanayi üretimi, Sabiha Gökçen çevresindeki havacılık hizmetleri, liman bağlantılı lojistik, teknik servis ve yoğun saha operasyonlarının aynı ilçede buluştuğu bir çalışma alanıdır. Bu çeşitlilik nedeniyle tek tip bir personel kıyafeti yaklaşımı yerine görev, vardiya, açık-kapalı alan dengesi ve kurumsal görünüm birlikte değerlendirilmelidir."; need="Üretim tesisimizin Pendik'te bulunması; numune görüşmesi, kumaş ve renk kontrolü, logo konumu değerlendirmesi ve tekrar sipariş standardının yüz yüze yürütülebilmesini kolaylaştırır. Yerel işletmeler ürün örneğini veya teknik dosyasını paylaşarak karar süresini kısaltabilir."; plan="Pendik'teki depo ve üretim ekiplerinde hareket kolaylığı sağlayan pantolonlar, görünürlüğü destekleyen yelekler ve mevsim geçişine uygun katmanlar öne çıkar. Müşteriyle temas eden servis personelinde ise temiz siluet, dengeli logo ölçüsü ve gün boyu formunu koruyan kumaşlar önem kazanır."; delivery="Pendik içindeki teslimatlar üretim planına ve sipariş kapsamına göre tek noktaya veya bölüm bazlı paketlerle organize edilebilir. Beden listesi, departman kodu ve teslim alacak yetkili baştan paylaşıldığında sayım ve dağıtım süreci daha kontrollü ilerler."; neighbors=@("tuzla-is-elbiseleri","kartal-is-elbiseleri","anadolu-yakasi-is-elbiseleri") },
  [ordered]@{ slug="pendik-personel-kiyafetleri"; place="Pendik"; target="Pendik personel kıyafetleri"; title="Pendik Personel Kıyafetleri | Kurumsal Üretim"; meta="Pendik personel kıyafetleri: departmana özel model, kurumsal renk, baskı ve nakış uygulaması. Fabrika, hizmet ve saha ekipleri için teklif alın."; hero="Pendik Personel Kıyafetleri"; lead="Çalışanların görevlerine ve markanızın kurumsal kimliğine uygun personel kıyafeti setlerini Pendik'teki tesisimizde planlıyor ve üretiyoruz."; areas="Kurtköy, Yenişehir, Çamçeşme, Esenyalı, Orhangazi ve Pendik merkez"; profile="Personel kıyafeti yalnızca iş sahasında kullanılan bir ürün değildir; çalışan deneyimini, marka algısını ve departmanların birbirinden ayırt edilmesini doğrudan etkiler. Pendik'teki kurumsal işletmeler için ön büro, teknik ekip, depo, üretim, sevkiyat ve temizlik personelinin ihtiyacı aynı proje içinde farklı ürün setleriyle ele alınabilir."; need="Beden dağılımı ve görev tanımı baştan ayrıştırıldığında gereksiz ürün alımı azalır. Kadın ve erkek kalıpları, masa başı ve hareketli görevler, yazlık-kışlık kullanım ile yıkama sıklığı birlikte incelenerek sürdürülebilir bir kıyafet standardı oluşturulur."; plan="Kurumsal görünüm isteyen ekiplerde polo tişört, sweatshirt, polar ve softshell gibi katmanlar aynı renk ailesinde kurgulanabilir. Üretim sahasında çalışan personel için cep yerleşimi, diz hareketi, reflektör ihtiyacı ve kumaş dayanımı ayrıca değerlendirilir; böylece görsel birlik işlevselliği sınırlamaz."; delivery="Pendik personel kıyafeti siparişlerinde ürünleri çalışan, departman veya lokasyon bazında etiketlemek mümkündür. Teslimat öncesinde koli içeriğinin planlanması, çok vardiyalı işletmelerde dağıtımı hızlandırır ve beden karışıklığını azaltır."; neighbors=@("pendik-is-elbiseleri","kartal-is-elbiseleri","sancaktepe-is-elbiseleri") },
  [ordered]@{ slug="tuzla-is-elbiseleri"; place="Tuzla"; target="Tuzla iş elbiseleri"; title="Tuzla İş Elbiseleri ve İş Kıyafeti Üretimi"; meta="Tuzla iş elbiseleri için tersane, organize sanayi, kimya ve lojistik ekiplerine özel üretim. Logo, nakış, reflektör ve toplu sipariş desteği."; hero="Tuzla İş Elbiseleri Üreticisi"; lead="Tuzla'daki tersane, organize sanayi, lojistik ve teknik operasyonlara çalışma koşullarına göre planlanmış kurumsal iş kıyafetleri sunuyoruz."; areas="Aydınlı, Orhanlı, Tepeören, İçmeler, Deri OSB ve tersaneler bölgesi"; profile="Tuzla'nın üretim yapısı; tersaneler, metal işleme, kimya, deri sanayi, depolama ve liman bağlantılı operasyonlarla yüksek teknik çeşitlilik gösterir. Kıyafet seçimi yapılırken yalnızca kurumsal renk değil; kıvılcım, kir, aşınma, açık alan, araç trafiği ve vardiya sıcaklıkları gibi gerçek saha koşulları değerlendirilmelidir."; need="Tuzla projelerinde departman bazlı risk farkı belirgindir. Aynı işletmede ofis ve ziyaretçi ekibi sade bir polo kullanırken bakım personeli takviyeli pantolon, saha çalışanı görünürlük sağlayan dış katman, kaynak bölümü ise göreve uygun koruyucu ürün gerektirebilir."; plan="Yoğun sanayi kullanımı için dikiş noktaları, fermuar ve çıtçıt seçimi, cep yükü ve yıkama yöntemi ürün ömrünü belirler. Numune yalnızca ayakta denenmemeli; eğilme, diz çökme, merdiven kullanma ve ekipmana erişme hareketleriyle kontrol edilmelidir."; delivery="Tuzla OSB ve tersaneler bölgesine yapılacak sevkiyatlarda güvenlik giriş prosedürü, teslim saati ve depo kabul bilgileri önceden planlanır. Büyük siparişler bölüm veya vardiya bazında ayrılarak teslim edildiğinde işletme içi dağıtım daha ölçülebilir hâle gelir."; neighbors=@("pendik-is-elbiseleri","kartal-is-elbiseleri","istanbul-is-elbiseleri") },
  [ordered]@{ slug="kartal-is-elbiseleri"; place="Kartal"; target="Kartal iş elbiseleri"; title="Kartal İş Elbiseleri | Kurumsal Personel Kıyafeti"; meta="Kartal iş elbiseleri ve personel kıyafetleri için özel üretim, logo baskı ve nakış. Teknik servis, sağlık, yapı ve hizmet ekiplerine çözümler."; hero="Kartal İş Elbiseleri Üreticisi"; lead="Kartal'daki teknik servislerden sağlık kuruluşlarına, yapı projelerinden hizmet ekiplerine kadar farklı görevler için kurumsal iş kıyafeti üretiyoruz."; areas="Yakacık, Soğanlık, Cevizli, Topselvi, Orhantepe ve Kartal merkez"; profile="Kartal'da dönüşen iş merkezleri, sağlık kampüsleri, teknik servisler, sahil hattındaki hizmet işletmeleri ve devam eden yapı projeleri farklı personel profillerini bir araya getirir. Bu nedenle kıyafet setinin hem müşteriye dönük alanlarda düzenli görünmesi hem de saha görevlerinde hareketi desteklemesi gerekir."; need="Teknik ekiplerde alet erişimi ve dayanım; sağlık ve temizlik personelinde sık yıkama ile rahatlık; güvenlik ve tesis yönetiminde ise görünürlük ve kurumsal temsil öne çıkar. Ürün seçimi departman görüşmeleriyle yapıldığında tek modelin farklı görevlerde yarattığı uyumsuzluk önlenebilir."; plan="Kartal için hazırlanacak projelerde polo tişört ve softshell gibi temsil gücü yüksek parçalar, iş pantolonu ve yelek gibi fonksiyonel ürünlerle aynı renk sistemi içinde eşleştirilebilir. Logo konumu dış katman giyildiğinde de görünür kalacak şekilde planlanmalıdır."; delivery="Kartal'a sevkiyatlarda saha şantiyesi, plaza kabul alanı veya sağlık tesisi deposu gibi teslim noktalarının prosedürü değişebilir. Adres, yetkili ve kabul saatinin sipariş formunda belirtilmesi, ürünlerin doğru birime kesintisiz ulaşmasına yardımcı olur."; neighbors=@("pendik-is-elbiseleri","maltepe-is-elbiseleri","anadolu-yakasi-is-elbiseleri") },
  [ordered]@{ slug="maltepe-is-elbiseleri"; place="Maltepe"; target="Maltepe iş elbiseleri"; title="Maltepe İş Elbiseleri ve Personel Kıyafetleri"; meta="Maltepe iş elbiseleri: restoran, otel, sağlık, eğitim, güvenlik ve teknik ekipler için kurumsal üretim, baskı, nakış ve teslimat desteği."; hero="Maltepe İş Elbiseleri Üreticisi"; lead="Maltepe'deki hizmet, eğitim, sağlık, yeme-içme ve tesis yönetimi ekiplerine marka kimliğiyle uyumlu personel kıyafetleri hazırlıyoruz."; areas="Küçükyalı, İdealtepe, Altayçeşme, Zümrütevler, Başıbüyük ve sahil hattı"; profile="Maltepe'nin iş yapısı hizmet sektörü, eğitim kurumları, sağlık işletmeleri, restoranlar, siteler ve teknik bakım ekipleri etrafında çeşitlenir. Müşteriyle doğrudan temasın yoğun olduğu bu alanlarda iş kıyafeti temiz bir görünüm sunarken uzun vardiyada konfor ve kolay bakım da sağlamalıdır."; need="Restoran ve kafelerde önlük ile üst giyim arasındaki renk dengesi, sağlık ve temizlik ekiplerinde yıkama dayanımı, okul personelinde güven veren sade tasarım, site yönetiminde ise görevlerin renk veya modelle ayrılması önemlidir. Her grup için aynı kumaşın kullanılması yerine kullanım sıklığı değerlendirilir."; plan="Maltepe personel setlerinde hafif polo tişört, mevsimlik polar, servis önlüğü ve sade softshell modelleri sık tercih edilir. Teknik personelin setine iş pantolonu ve yelek eklenirken, logo ölçüsü müşteriye dönük alanlarda abartısız ve okunaklı tutulur."; delivery="Maltepe'deki çok bloklu site, kampüs ve eğitim kurumlarında teslimatın merkez depoya mı yoksa birimlere mi yapılacağı önceden netleştirilir. İsim veya departman etiketli paketleme, özellikle dönem başı ve toplu işe giriş süreçlerinde dağıtımı kolaylaştırır."; neighbors=@("kartal-is-elbiseleri","atasehir-is-elbiseleri","anadolu-yakasi-is-elbiseleri") },
  [ordered]@{ slug="umraniye-is-elbiseleri"; place="Ümraniye"; target="Ümraniye iş elbiseleri"; title="Ümraniye İş Elbiseleri | Özel Üretim ve Logo"; meta="Ümraniye iş elbiseleri için sanayi, depo, teknik servis, plaza ve tesis ekiplerine özel üretim. Logo baskı, nakış ve kurumsal teklif desteği."; hero="Ümraniye İş Elbiseleri Üreticisi"; lead="Ümraniye'deki sanayi işletmeleri, depolar, teknik servisler ve kurumsal tesisler için görev odaklı personel kıyafetleri üretiyoruz."; areas="Dudullu, İMES, Yukarı Dudullu, Çakmak, Ihlamurkuyu ve Şerifali çevresi"; profile="Ümraniye; İMES ve Dudullu çevresindeki üretim işletmeleriyle finans merkezlerine yakın ofis, depo ve tesis hizmetlerini aynı bölgede barındırır. Bu yapı, ağır kullanıma uygun saha ürünleri ile kurumsal temsil gücü yüksek servis kıyafetlerinin tek tedarik planında yönetilmesini gerektirir."; need="Atölye çalışanlarında sürtünme ve cep kullanımı, depo ekiplerinde hareket ve görünürlük, teknik servislerde müşteri alanına uygun görünüm, plaza destek ekiplerinde ise sade renk ve kolay bakım öne çıkar. Kıyafet standardı görev tanımıyla eşleştirildiğinde ürün ömrü ve çalışan kabulü artar."; plan="Ümraniye projelerinde iş pantolonu, polo tişört, sweatshirt ve softshell katmanları bölüm renkleriyle planlanabilir. Alet taşıyan ekiplerde cep hacmi dengelenmeli, makine çevresinde çalışanlarda sarkan aksesuarlar sınırlandırılmalı ve numune gerçek hareketlerle denenmelidir."; delivery="İMES, Dudullu OSB ve Şerifali çevresinde depo kabul saatleri ile araç giriş kuralları değişebilir. Teslimat planına iletişim kişisi ve rampa bilgisi eklenmesi, yüksek adetli kolilerin beklemeden doğru bölüme alınmasını sağlar."; neighbors=@("atasehir-is-elbiseleri","sancaktepe-is-elbiseleri","anadolu-yakasi-is-elbiseleri") },
[ordered]@{ slug="sancaktepe-is-elbiseleri"; place="Sancaktepe"; target="Sancaktepe iş elbiseleri"; title="Sancaktepe İş Elbiseleri ve Toplu Üretim"; meta="Sancaktepe iş elbiseleri: üretim, inşaat, lojistik, sağlık ve belediye ekiplerine özel model, kurumsal renk, baskı ve nakış seçenekleri."; hero="Sancaktepe İş Elbiseleri Üreticisi"; lead="Sancaktepe'de büyüyen üretim, lojistik, yapı ve sağlık operasyonları için dayanıklı ve kurumsal personel kıyafetleri hazırlıyoruz."; areas="Sarıgazi, Samandıra, Yenidoğan, Eyüp Sultan, Emek ve Abdurrahmangazi"; profile="Sancaktepe'de sanayi atölyeleri, lojistik bağlantılar, yeni yapı alanları, belediye hizmetleri ve sağlık kampüsleri geniş bir saha personeli kitlesi oluşturur. Açık alanda çalışma, araçla hareket, yoğun fiziksel aktivite ve mevsim değişimi ürün setinin temel kararlarıdır."; need="Saha ekiplerinde görünürlük ve katmanlama, inşaat görevlerinde aşınma bölgeleri, lojistik personelinde cepler ile hareket serbestliği, sağlık destek hizmetlerinde ise hijyen ve kolay yıkama önceliklidir. Her bölüm için ürün miktarı çalışan sayısı ve yedekleme ihtiyacıyla hesaplanır."; plan="Sancaktepe iş kıyafeti seti yazlık tişört, dayanıklı pantolon, reflektörlü yelek, polar ve yağmurluk gibi tamamlayıcı parçalardan kurulabilir. Renk blokları ve logo yerleşimi, personelin uzaktan tanınmasını desteklerken kurum kimliğini koruyacak ölçüde tasarlanır."; delivery="Şantiye veya saha teslimatlarında sabit depo bulunmayabileceği için teslim koordinatının, saha sorumlusunun ve uygun zaman aralığının yazılı paylaşılması önemlidir. Bölünmüş teslim gerekiyorsa her partinin ürün ve beden dökümü ayrıca hazırlanır."; neighbors=@("umraniye-is-elbiseleri","pendik-is-elbiseleri","anadolu-yakasi-is-elbiseleri") },
  [ordered]@{ slug="atasehir-is-elbiseleri"; place="Ataşehir"; target="Ataşehir iş elbiseleri"; title="Ataşehir İş Elbiseleri | Kurumsal Personel Üretimi"; meta="Ataşehir iş elbiseleri ve kurumsal personel kıyafetleri. Plaza, restoran, güvenlik, tesis, sağlık ve teknik ekipler için baskılı ve nakışlı üretim."; hero="Ataşehir İş Elbiseleri Üreticisi"; lead="Ataşehir'deki plaza, finans, yeme-içme, güvenlik ve tesis yönetimi ekipleri için profesyonel görünümü destekleyen kıyafet setleri üretiyoruz."; areas="Kozyatağı, İçerenköy, Kayışdağı, Küçükbakkalköy, Barbaros ve Finans Merkezi çevresi"; profile="Ataşehir'de kurumsal ofisler, finans kuruluşları, rezidanslar, alışveriş ve yeme-içme işletmeleri yoğun müşteri teması olan personel grupları yaratır. Kıyafetlerde işlev kadar marka dili, temiz siluet, renk tutarlılığı ve farklı departmanların uyumlu görünmesi de önem taşır."; need="Resepsiyon ve karşılama ekipleriyle teknik bakım personeli aynı tesiste çalışsa da hareket, cep ve kumaş ihtiyaçları farklıdır. Güvenlik, temizlik, mutfak ve vale ekipleri için görev bazlı model seçilirken renk paleti ve logo uygulaması bütüncül biçimde korunabilir."; plan="Ataşehir projelerinde polo yaka tişört, ince triko veya sweatshirt, softshell mont, servis önlüğü ve teknik pantolon farklı görev setleri olarak eşleştirilebilir. Nakışın iplik tonu, baskının ölçüsü ve ürün üzerindeki konumu kurumsal kimlik kılavuzuyla birlikte değerlendirilir."; delivery="Plaza ve rezidans teslimatlarında yükleme alanı rezervasyonu, güvenlik kaydı ve teslim katı gibi ayrıntılar önemlidir. Ürünlerin departman bazlı kolilenmesi, tesis yönetiminin kıyafetleri farklı hizmet sağlayıcılara hızlı ve kayıtlı biçimde dağıtmasını sağlar."; neighbors=@("umraniye-is-elbiseleri","maltepe-is-elbiseleri","anadolu-yakasi-is-elbiseleri") },
  [ordered]@{ slug="istanbul-is-elbiseleri"; place="İstanbul"; target="İstanbul iş elbiseleri"; title="İstanbul İş Elbiseleri Üreticisi | Kurumsal Çözümler"; meta="İstanbul iş elbiseleri üretimi: Avrupa ve Anadolu Yakası'ndaki firmalara özel model, baskı, nakış, numune, toplu üretim ve planlı teslimat."; hero="İstanbul İş Elbiseleri Üreticisi"; lead="İstanbul genelindeki tek veya çok lokasyonlu işletmelere kurumsal kimliğe, görev koşullarına ve teslimat planına uygun iş kıyafetleri üretiyoruz."; areas="İstanbul Anadolu Yakası, Avrupa Yakası ve Türkiye geneli sevkiyat ağı"; profile="İstanbul'da üretim tesisinden otele, lojistik merkezinden sağlık kuruluşuna, restorandan kurumsal ofise kadar çok farklı çalışma modeli bulunur. Çok lokasyonlu işletmelerde ortak marka görünümü korunurken iklim, görev, vardiya ve bina koşullarına göre ürün setlerinin esnek olması gerekir."; need="Merkezi satın alma yapan firmalar için ürün kodu, kumaş, renk, logo, beden tablosu ve paketleme standardının tek dosyada tutulması tekrar siparişleri kolaylaştırır. Şubeler arasında farklı ürün adları kullanılmasının önüne geçilmesi, stok ve bütçe raporlarını daha güvenilir hâle getirir."; plan="İstanbul ölçeğindeki projelerde çekirdek bir üst giyim ve pantolon standardı kurulup saha, mutfak, teknik servis, güvenlik ve yönetim ekiplerine özel tamamlayıcı parçalar eklenebilir. Numune seti farklı lokasyonlardan kullanıcılarla denendiğinde ortak kalıp kararı daha sağlıklı verilir."; delivery="İstanbul içindeki trafik, tesis kabul saatleri ve çoklu depo yapısı sevkiyatın üretim kadar dikkatli planlanmasını gerektirir. Tek merkez teslimi, şube bazlı dağıtım veya dönemsel parti sevkiyatı seçenekleri sipariş öncesinde belirlenerek koli etiketlerine yansıtılır."; neighbors=@("anadolu-yakasi-is-elbiseleri","pendik-is-elbiseleri","tuzla-is-elbiseleri") },
  [ordered]@{ slug="anadolu-yakasi-is-elbiseleri"; place="Anadolu Yakası"; target="Anadolu Yakası iş elbiseleri"; title="Anadolu Yakası İş Elbiseleri | Kardeşler Tekstil"; meta="Anadolu Yakası iş elbiseleri için Pendik'ten doğrudan üretim. İlçe ve lokasyon bazlı kurumsal kıyafet, logo, numune ve teslimat planı."; hero="Anadolu Yakası İş Elbiseleri Üreticisi"; lead="Pendik'teki üretim merkezimizden Anadolu Yakası'nın sanayi, hizmet, sağlık, lojistik ve kurumsal işletmelerine özel iş kıyafetleri sunuyoruz."; areas="Pendik, Tuzla, Kartal, Maltepe, Ataşehir, Ümraniye, Sancaktepe ve çevre ilçeler"; profile="Anadolu Yakası; doğuda tersane ve organize sanayi bölgelerinden merkezde finans, sağlık, eğitim ve hizmet işletmelerine uzanan geniş bir ekonomik hat oluşturur. İlçeler arasındaki görev ve çalışma ortamı farkı, kurumsal kıyafet programının ortak standart ile yerel ihtiyaç arasında dengelenmesini gerektirir."; need="Birden fazla ilçede ekibi bulunan firmalar için aynı ürün kodlarının ve logo standardının kullanılması marka bütünlüğü sağlar. Buna karşılık Tuzla'daki ağır saha ekibiyle Ataşehir'deki tesis personeline aynı kumaşı vermek yerine görev riskine göre farklılaştırılmış setler tanımlanmalıdır."; plan="Anadolu Yakası projelerinde merkezi numune onayı Pendik tesisimizde yürütülebilir; ardından beden listeleri lokasyon bazında ayrılır. Polo tişört, iş pantolonu ve softshell gibi çekirdek ürünlere sektörün gerektirdiği önlük, reflektörlü yelek, polar veya yağmurluk eklenebilir."; delivery="Yakaya yayılmış ekiplerde ürünlerin tek depoya gönderilmesi kadar her ilçeye ayrı sevk edilmesi de mümkündür. Lokasyon kodu, teslim yetkilisi ve koli içeriği eşleştirildiğinde dağıtım hataları azalır; yeni çalışan ihtiyaçları aynı standart üzerinden tamamlanabilir."; neighbors=@("istanbul-is-elbiseleri","pendik-is-elbiseleri","umraniye-is-elbiseleri") }
)

# Pendik personel kıyafetleri, ayrı URL yerine Pendik ana sayfasında ikincil sorgu olarak hedeflenir.
$locations = @($locations | Where-Object { $_.slug -ne "pendik-personel-kiyafetleri" })

$sectors = @("Fabrikalar","İnşaat","Lojistik","Restoran","Kafe","Otel","Güvenlik","Sağlık","Belediye","Eğitim")
$products = @(
  @{name="Polo Yaka Tişört";slug="polo-yaka-is-tisortu"}, @{name="İş Pantolonu";slug="is-pantolonu"},
  @{name="Softshell Mont";slug="softshell-is-montu"}, @{name="Şef Kıyafeti";slug="asci-kiyafeti-is-onlugu"},
  @{name="Reflektörlü Yelek";slug="reflektorlu-is-yelegi"}, @{name="Polar";slug="polar-is-montu"},
  @{name="Yağmurluk";slug="is-guvenligi-ekipmanlari"}
)

function H([string]$value) { return [Net.WebUtility]::HtmlEncode($value) }
function LinkName([string]$slug) {
  $item = $locations | Where-Object { $_.slug -eq $slug } | Select-Object -First 1
  if ($item) { return $item.place + " İş Elbiseleri" }
  return $slug
}

foreach ($loc in $locations) {
  $context = switch ($loc.slug) {
    "pendik-is-elbiseleri" { "havacılık bağlantılı lojistik, üretim tesisi ve teknik saha düzeni" }
    "pendik-personel-kiyafetleri" { "departman ayrımı, çalışan deneyimi ve kurumsal temsil düzeni" }
    "tuzla-is-elbiseleri" { "tersane, ağır sanayi ve organize sanayi çalışma koşulları" }
    "kartal-is-elbiseleri" { "sağlık kampüsü, teknik servis ve dönüşen yapı projeleri" }
    "maltepe-is-elbiseleri" { "hizmet, eğitim, sağlık ve yeme-içme operasyonları" }
    "umraniye-is-elbiseleri" { "İMES-Dudullu sanayi hattı ile plaza destek hizmetleri" }
    "sancaktepe-is-elbiseleri" { "açık saha, lojistik, yapı ve belediye hizmetleri" }
    "atasehir-is-elbiseleri" { "finans merkezi, rezidans ve müşteri temaslı tesis hizmetleri" }
    "istanbul-is-elbiseleri" { "iki yakaya yayılan çok lokasyonlu ve çok sektörlü organizasyonlar" }
    "anadolu-yakasi-is-elbiseleri" { "sanayi ilçeleriyle finans ve hizmet merkezlerini birleştiren bölgesel yapı" }
  }
  $contextSentence = $context.Substring(0,1).ToUpperInvariant() + $context.Substring(1)
  $sectorLens = switch ($loc.slug) {
    "pendik-is-elbiseleri" { "havaalanı, depo ve üretim hattı geçişlerinde" }
    "tuzla-is-elbiseleri" { "tersane, OSB ve liman bağlantılı sahalarda" }
    "kartal-is-elbiseleri" { "sağlık, teknik servis ve yapı alanlarında" }
    "maltepe-is-elbiseleri" { "kampüs, sahil ve hizmet noktalarında" }
    "umraniye-is-elbiseleri" { "atölye, depo ve plaza geçişlerinde" }
    "sancaktepe-is-elbiseleri" { "şantiye, lojistik ve açık saha görevlerinde" }
    "atasehir-is-elbiseleri" { "plaza, rezidans ve müşteri alanlarında" }
    "istanbul-is-elbiseleri" { "iki yakaya yayılan farklı operasyonlarda" }
    "anadolu-yakasi-is-elbiseleri" { "ilçeler arası saha ve hizmet ağında" }
  }
  $sectorShift = [array]::IndexOf($locations, $loc) % $sectors.Count
  if ($sectorShift -eq 0) { $sectorOrder = $sectors } else { $sectorOrder = @($sectors[$sectorShift..($sectors.Count-1)] + $sectors[0..($sectorShift-1)]) }
  $sectorCards = foreach ($sector in $sectorOrder) {
    $focus = switch ($sector) {
      "Fabrikalar" { "vardiya düzeni, dayanım, cep kullanımı ve bölüm renklerinin" }
      "İnşaat" { "açık alan, görünürlük, katmanlama ve aşınma noktalarının" }
      "Lojistik" { "araç trafiği, depo hareketi, gece vardiyası ve paket erişiminin" }
      "Restoran" { "mutfak ısısı, servis görünümü, leke yönetimi ve kolay bakımın" }
      "Kafe" { "marka rengi, hareket rahatlığı, önlük düzeni ve sık yıkamanın" }
      "Otel" { "departman ayrımı, misafir teması, temsil ve vardiya konforunun" }
      "Güvenlik" { "uzun vardiya, dış ortam, görünürlük ve kurumsal duruşun" }
      "Sağlık" { "hijyen, sık yıkama, rahat hareket ve görev ayrımının" }
      "Belediye" { "saha görünürlüğü, hava koşulları, ekip tanımı ve dayanımın" }
      "Eğitim" { "güven veren görünüm, kolay bakım, kampüs görevi ve mevsimin" }
    }
    "<article><h3>$(H $sector)</h3><p>$(H $loc.place) $sector ekiplerinde $sectorLens $focus görev bazında değerlendirilmesi gerekir.</p></article>"
  }
  $productCards = for ($i=0; $i -lt $products.Count; $i++) {
    $p = $products[$i]
    $copy = switch ($p.name) {
      "Polo Yaka Tişört" { "$($loc.place) bölgesinde müşteri teması ve günlük ekip kullanımı için kurumsal renkte logolu üst giyim." }
      "İş Pantolonu" { "$($loc.place) görevlerinde cep, hareket ve kumaş dayanımını dengeleyen iş pantolonları." }
      "Softshell Mont" { "$($loc.place) mevsim geçişlerinde saha ve servis ekipleri için düzenli dış katman." }
      "Şef Kıyafeti" { "$($loc.place) yeme-içme ekiplerinde sıcaklık, leke ve kurum çizgisini dengeleyen modeller." }
      "Reflektörlü Yelek" { "$($loc.place) araç trafiği ve düşük ışık görevlerinde görünürlüğü destekleyen yelekler." }
      "Polar" { "$($loc.place) depo, açık alan ve vardiya kullanımına uygun sıcak ara katman." }
      "Yağmurluk" { "$($loc.place) açık saha görevlerinde yağış ve hareket ihtiyacını tamamlayan ürün." }
    }
    "<a class=`"local-product-card`" href=`"../$($p.slug)/`"><h3>$(H $p.name)</h3><p>$(H $copy)</p><strong>Ürün detayını inceleyin →</strong></a>"
  }
  $nearby = foreach ($slug in $loc.neighbors) { "<a href=`"../$slug/`">$(H (LinkName $slug))</a>" }
  $faq = @(
    @{q="$($loc.place) bölgesine teslimat yapıyor musunuz?";a="Evet. $($loc.areas) başta olmak üzere $($loc.place) ve çevresindeki kurumsal adreslere planlı sevkiyat yapıyoruz. Teslim noktası, kabul saati ve paketleme biçimi teklif aşamasında netleştirilir."},
    @{q="$($loc.place) siparişlerinde minimum adet nedir?";a="Özel üretimde minimum sipariş 50 adettir. $($loc.place) projesinde ürün adedi, beden dağılımı ve model kapsamı aynı planda değerlendirilebilir."},
    @{q="$($loc.place) kurumsal logoları için baskı ve nakış yapıyor musunuz?";a="Evet. $($loc.place) ekiplerinin kumaş ve yıkama koşuluna göre logo incelenir; nakış, DTF, transfer veya serigrafiden uygun yöntem seçilir."},
    @{q="$($loc.place) projesinde seri üretimden önce numune hazırlanabilir mi?";a="Projenin kapsamına göre numune planlanabilir. $($loc.place) kullanımı için kalıp, kumaş, renk, cep ve logo onaylanınca üretim aynı referansla ilerler."},
    @{q="$($loc.place) ekipleri için çoklu ürün seti oluşturabilir miyiz?";a="Evet. $($loc.place) için üst giyim, pantolon, yelek, polar, mont ve göreve özel parçalar tek listede toplanabilir; departman ayrımı dağıtımı kolaylaştırır."},
    @{q="$($loc.place) projesinde kumaş ve kurumsal renk nasıl seçilir?";a="$contextSentence için çalışma sıcaklığı, hareket yoğunluğu, yıkama sıklığı ve kurum renkleri birlikte değerlendirilir. Kartela ve numune üzerinden yapılan kontrol, ekrandaki renkle gerçek kumaş arasındaki farkın üretimden önce görülmesini sağlar."},
    @{q="$($loc.place) için yazılı kurumsal teklif nasıl alınır?";a="Teklif formunda ürün tipi, yaklaşık adet, teslimat şehri ve hedef tarih paylaşılabilir; logo veya şartname dosyası da eklenebilir. $contextSentence ayrıntıları incelendikten sonra kapsamın netleşmesi için firma yetkilisiyle iletişim kurulur."}
  )
  $faqHtml = foreach ($item in $faq) { "<details><summary>$(H $item.q)</summary><p>$(H $item.a)</p></details>" }
  $faqSchema = @{"@context"="https://schema.org";"@type"="FAQPage";mainEntity=@($faq | ForEach-Object {@{"@type"="Question";name=$_.q;acceptedAnswer=@{"@type"="Answer";text=$_.a}}})} | ConvertTo-Json -Compress -Depth 8
  $localSchema = @{"@context"="https://schema.org";"@type"="Service";"@id"="https://kardeslertekstil.com.tr/$($loc.slug)/#service";name=$loc.hero;url="https://kardeslertekstil.com.tr/$($loc.slug)/";serviceType="Kurumsal iş kıyafeti üretimi";provider=@{"@id"="https://kardeslertekstil.com.tr/#organization"};areaServed=@{"@type"="AdministrativeArea";name=$loc.place}} | ConvertTo-Json -Compress -Depth 6
  $breadcrumb = @{"@context"="https://schema.org";"@type"="BreadcrumbList";itemListElement=@(@{"@type"="ListItem";position=1;name="Ana Sayfa";item="https://kardeslertekstil.com.tr/"},@{"@type"="ListItem";position=2;name=$loc.target;item="https://kardeslertekstil.com.tr/$($loc.slug)/"})} | ConvertTo-Json -Compress -Depth 6
  $mailSubject = [Uri]::EscapeDataString("$($loc.place) Kurumsal Teklif Talebi")
  $waText = [Uri]::EscapeDataString("Merhaba, $($loc.target) için kurumsal teklif almak istiyorum.")
  $formMessage = [Uri]::EscapeDataString("$($loc.place) lokasyonundaki ekibimiz için yazılı iş kıyafeti teklifi almak istiyorum.")

  $html = @"
<!doctype html>
<html lang="tr"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>$(H $loc.title)</title><meta name="description" content="$(H $loc.meta)"><meta name="robots" content="index,follow,max-image-preview:large">
<link rel="canonical" href="https://kardeslertekstil.com.tr/$($loc.slug)/"><link rel="stylesheet" href="../styles.css?v=20260804-26">
<meta property="og:type" content="website"><meta property="og:locale" content="tr_TR"><meta property="og:site_name" content="Kardeşler Tekstil"><meta property="og:title" content="$(H $loc.title)"><meta property="og:description" content="$(H $loc.meta)"><meta property="og:url" content="https://kardeslertekstil.com.tr/$($loc.slug)/"><meta property="og:image" content="https://kardeslertekstil.com.tr/assets/logo-kit-badge.webp">
<meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="$(H $loc.title)"><meta name="twitter:description" content="$(H $loc.meta)"><meta name="twitter:image" content="https://kardeslertekstil.com.tr/assets/logo-kit-badge.webp"><script type="application/ld+json">$localSchema</script><script type="application/ld+json">$breadcrumb</script><script type="application/ld+json">$faqSchema</script>
<link rel="icon" type="image/png" sizes="48x48" href="/favicon-48x48.png?v=13"><link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png?v=13"><link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png?v=13"><link rel="shortcut icon" href="/favicon.ico?v=13"><link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png?v=13"><link rel="manifest" href="/manifest.webmanifest?v=13"><meta name="theme-color" content="#f97316"><meta name="google-analytics-id" content=""><script src="/site.js?v=20260804-12" defer></script></head>
<body class="local-page" data-screen-label="Local SEO"><header class="site-header"><div class="container"><a class="brand" href="../"><img src="../assets/logo-kit-badge.webp" alt="Kardeşler Tekstil"></a><nav class="nav" aria-label="Ana navigasyon"><a href="../">Ana Sayfa</a><a href="../urunlerimiz">Ürünlerimiz</a><a href="../referanslarimiz">Referanslarımız</a><a href="../hakkimizda">Hakkımızda</a><a href="../bilgi-merkezi/">Bilgi Merkezi</a><a href="../iletisim">İletişim</a></nav><a class="btn btn-accent" href="https://wa.me/902163961988" target="_blank" rel="noopener">Teklif Al</a></div></header>
<main><section class="page-head local-hero"><div class="container"><div class="eyebrow eyebrow-accent">$(H $loc.place) / İstanbul</div><h1>$(H $loc.hero)</h1><p>$(H $loc.lead)</p><div class="cta-row"><a class="btn btn-whatsapp" href="https://wa.me/902163961988?text=$waText" target="_blank" rel="noopener">WhatsApp ile Görüşün</a><a class="btn btn-quote-form" href="../iletisim?urun=%C3%96zel%20Tasar%C4%B1m&amp;mesaj=$formMessage#teklif-formu">Teklif İsteyin</a></div></div></section>
<section class="local-section"><div class="container local-two-col"><div><div class="eyebrow eyebrow-accent">BÖLGEYE ÖZEL PLANLAMA</div><h2>$(H $loc.place) için iş kıyafeti yaklaşımımız</h2><p>$(H $loc.profile)</p><p>$(H $loc.need)</p><p>$(H $loc.plan)</p><p>$(H $loc.place) satın alma ekipleri teklif toplarken yalnız birim fiyatı değil, $context nedeniyle ürünün kullanım ömrünü, çalışan tarafından kabulünü, sonraki beden ihtiyaçlarını ve aynı standardın yeniden üretilebilir olmasını da değerlendirmelidir. Açık teknik tanım, numune kararı ve düzenli ürün kodları bu karşılaştırmayı kolaylaştırır.</p></div><aside class="local-service-note"><strong>Hizmet alanı</strong><p>$(H $loc.areas)</p><span>Minimum 50 adet · Özel üretim · Logo uygulaması</span></aside></div></section>
<section class="local-section local-section-muted"><div class="container"><div class="section-head"><div><div class="eyebrow eyebrow-accent">NEDEN KARDEŞLER TEKSTİL</div><h2>$(H $loc.place) satın alması için kontrollü üretim</h2></div><p>$context içinde ihtiyacı kullanım koşulu ve tekrar sipariş standardıyla ele alıyoruz.</p></div><div class="local-benefit-grid"><article><h3>Özel üretim</h3><p>$(H $loc.place) ekipleri için kalıp, renk, cep ve aksesuar ayrıntılarını planlarız.</p></article><article><h3>Logo baskı</h3><p>$(H $loc.place) kumaşına ve logoya uygun baskı tekniğini üretimle birlikte uygularız.</p></article><article><h3>Nakış</h3><p>$(H $loc.place) kurumsal iplik tonu, ölçü ve yerleşimini ürün üzerinde kontrol ederiz.</p></article><article><h3>Kurumsal çözümler</h3><p>$(H $loc.place) departmanları için ortak ürün kodu ve renk sistemi kurarız.</p></article><article><h3>Toplu üretim</h3><p>$(H $loc.place) beden dağılımını onaylı numuneye bağlı üretim akışıyla yönetiriz.</p></article><article><h3>Türkiye geneli teslimat</h3><p>$(H $loc.place) merkezli siparişleri belirlenen paketleme planıyla sevk ederiz.</p></article></div></div></section>
<section class="local-section"><div class="container"><div class="section-head"><div><div class="eyebrow eyebrow-accent">SEKTÖREL ÇÖZÜMLER</div><h2>$(H $loc.place) bölgesinde hangi sektörlere üretim yapıyoruz?</h2></div><p>$contextSentence içindeki hareket, bakım, görünürlük ve temsil farklarını dikkate alarak $(H $loc.place) ürün setlerini görev bazında oluşturuyoruz.</p></div><div class="local-sector-grid">$($sectorCards -join '')</div></div></section>
<section class="local-section local-section-dark"><div class="container"><div class="section-head"><div><div class="eyebrow eyebrow-accent">ÜRÜN SEÇİMİ</div><h2>$(H $loc.place) ekipleri için ürün grupları</h2></div><p>$context için uygun model kodlarını inceleyip ürünleri $(H $loc.place) çoklu Teklif Listesi'ne ekleyebilirsiniz.</p></div><div class="local-product-grid">$($productCards -join '')</div></div></section>
<section class="local-section"><div class="container local-two-col"><div><div class="eyebrow eyebrow-accent">TEKLİFTEN TESLİMATA</div><h2>$(H $loc.place) projesini nasıl planlıyoruz?</h2><p>İlk görüşmede $context çerçevesinde çalışan sayısı, görev grupları, ürün tipi, mevsim, hedef tarih, beden bilgisi ve logo dosyası alınır. Bu veriler yanlış kumaş veya model seçimini önlemek için kullanılır.</p><p>$context için $(H $loc.place) model ve kumaşı netleşince baskı ya da nakış tekniği belirlenir. Numunede hareket, beden, cep, kapama ve görsel yerleşim kontrol edilerek yazılı onay teknik referansa dönüştürülür.</p><p>Kesimden kalite kontrole kadar tamamlanan $($loc.target) ürünleri, bölgedeki departman veya vardiya planına göre paketlenir. Tekrar siparişlerde aynı kod ve onay bilgisinin kullanılması kurum görünümünü korur.</p></div><div><div class="eyebrow eyebrow-accent">LOJİSTİK VE DAĞITIM</div><h2>$(H $loc.place) teslimat planı</h2><p>$(H $loc.delivery)</p><p>$(H $loc.place) hedef tarihi formda paylaşıldığında kumaş, aksesuar, numune ve üretim kapasitesi $context açısından değerlendirilir. Acil projelerde sabit teknik ayrıntıların açıkça belirtilmesi gerçekçi takvim kurulmasını sağlar.</p></div></div></section>
<section class="local-section local-section-muted"><div class="container local-two-col"><div><div class="eyebrow eyebrow-accent">KALİTE VE SÜREKLİLİK</div><h2>$(H $loc.place) için sürdürülebilir standart</h2><p>$context kapsamında kıyafetin başarısı yalnız ilk teslimat görünümüyle ölçülmez. Kumaşın yıkama davranışı, dikişlerin görev hareketine dayanması, logonun korunması ve yeni çalışan için aynı modelin yeniden üretilebilmesi izlenir.</p></div><div><div class="eyebrow eyebrow-accent">YAKIN HİZMET BÖLGELERİ</div><h2>$(H $loc.place) çevresindeki çözümler</h2><p>$context dışında farklı ilçelerde ekibiniz bulunuyorsa bağlantılı hizmet sayfalarımızdan bölgesel planlama ayrıntılarını inceleyebilirsiniz.</p><nav class="local-neighbor-links" aria-label="Yakın hizmet bölgeleri">$($nearby -join '')</nav></div></div></section>
<section class="local-section"><div class="container local-faq"><div class="section-head"><div><div class="eyebrow eyebrow-accent">SIK SORULAN SORULAR</div><h2>$(H $loc.place) iş elbiseleri hakkında</h2></div><p>$context için teklif öncesinde değerlendirilen üretim, logo, adet ve teslimat başlıkları.</p></div>$($faqHtml -join '')</div></section>
<section class="local-final-cta"><div class="container"><div><div class="eyebrow eyebrow-accent">KURUMSAL TEKLİF</div><h2>$(H $loc.place) ekibiniz için üretimi birlikte planlayalım.</h2><p>$context doğrultusunda ürün listenizi, adedinizi, logonuzu ve hedef tarihinizi paylaşın; $(H $loc.place) yazılı teklif sürecini başlatalım.</p></div><div class="local-cta-actions"><a class="btn btn-whatsapp" href="https://wa.me/902163961988?text=$waText" target="_blank" rel="noopener">WhatsApp</a><a class="btn btn-quote-form" href="../iletisim?urun=%C3%96zel%20Tasar%C4%B1m&amp;mesaj=$formMessage#teklif-formu">Teklif Formu</a><a class="btn btn-secondary-dark" href="mailto:kardesler@kardeslertekstil.com.tr?subject=$mailSubject">E-posta</a></div></div></section></main>
<footer class="site-footer"><div class="container grid"><div><img class="footer-logo" src="../assets/logo-kit-badge.webp" alt="Kardeşler Tekstil"><p class="tagline">1982'den bu yana kurumsal firmalara özel iş kıyafeti üretiyoruz.</p></div><div><h4>Site</h4><a href="../">Ana Sayfa</a><a href="../urunlerimiz">Ürünlerimiz</a><a href="../referanslarimiz">Referanslarımız</a><a href="../hakkimizda">Hakkımızda</a><a href="../bilgi-merkezi/">Bilgi Merkezi</a></div><div><h4>İletişim</h4><div class="ico-row">Fevzi Çakmak, Ulukapı Sk. 11-12/A, Pendik / İstanbul</div><div class="ico-row"><a href="tel:+902163961988">0216 396 19 88</a></div><div class="ico-row"><a href="mailto:kardesler@kardeslertekstil.com.tr?subject=Kurumsal%20Teklif%20Talebi">kardesler@kardeslertekstil.com.tr</a></div></div><div><h4><a href="https://wa.me/902163961988" target="_blank" rel="noopener">Hızlı Teklif</a></h4><a class="btn btn-whatsapp" href="https://wa.me/902163961988" target="_blank" rel="noopener">WhatsApp'tan Teklif Al</a></div></div><div class="bottom"><span>© 2026 Kardeşler Tekstil A.Ş.</span><span>EST. 1982 · Pendik / İstanbul</span></div></footer></body></html>
"@
  $targetDir = Join-Path $siteRoot $loc.slug
  New-Item -ItemType Directory -Path $targetDir -Force | Out-Null
  $html = $html.Replace("<p>$context ", "<p>$contextSentence ")
  if ($html -match 'Ã|Ä|Å|Â|â€|&#19[567];|&#196;|&#197;') {
    throw "Bozuk Türkçe karakter algılandı: $($loc.slug)"
  }
  [IO.File]::WriteAllText((Join-Path $targetDir "index.html"), $html, $utf8)
}

Write-Output "Generated $($locations.Count) location pages."
