param([string]$SiteRoot)
$ErrorActionPreference = 'Stop'
$root = if ($SiteRoot) { (Resolve-Path $SiteRoot).Path } else { Split-Path $PSScriptRoot -Parent }
$utf8 = [Text.UTF8Encoding]::new($false)
$sections = @{
  'duyusal-konfor-odakli-is-kiyafeti' = @('Duyusal konfor denemesi nasıl kaydedilir?','Pilot denemede yaka, manşet, bel, etiket ve dikiş temas noktaları ayrı ayrı puanlanmalıdır. Değerlendirme aynı vardiya süresi, iç katman ve ortam sıcaklığında tekrarlanmalı; kaşıntı, baskı, sürtünme, ter tutma veya ses gibi bildirimler ürün bölgesiyle eşleştirilmelidir. Yalnız genel memnuniyet puanı almak sorunun kaynağını göstermez. Farklı bedenlerden ve görevlerden temsilci çalışanların notları anonim kodlarla tutulabilir. Bir ayrıntı değiştirildiğinde kumaş, iplik, etiket yerleşimi ve kalıp revizyonu birlikte kaydedilmeli; yeni numune eski sürümle aynı koşulda karşılaştırılmalıdır. Sağlıkla ilgili bir rahatsızlık bildirimi ürün seçimi notu olarak yorumlanmamalı, işyeri sağlık birimine yönlendirilmelidir. Böylece konfor iyileştirmesi kişisel tahmine değil tekrarlanabilir saha gözlemine dayanır.')
  'is-kiyafeti-iade-lojistigi' = @('İade hareketi için asgari kayıt alanları','Her iade paketinde çalışan adı yerine personel veya zimmet kodu, ürün kodu, beden, adet, iade nedeni, teslim tarihi ve ürün durumu bulunmalıdır. Kullanılmamış, beden değişimi isteyen, tamir edilebilir, hijyen nedeniyle ayrılması gereken ve üretim hatası şüphesi taşıyan parçalar aynı akışta işlenmemelidir. Kabul noktasında fotoğraf ve teslim alan kişi kaydı oluşturulması, eksik paket tartışmasını azaltır. İade edilen ürün yeniden stoğa girecekse temizlik, koku, leke, aksesuar ve deformasyon kontrolü tamamlanmadan kullanılabilir statüsü verilmemelidir. Haftalık raporda neden kodları ürün ve beden kırılımında izlenirse yanlış beden dağılımı ile gerçek kalite sorunu ayrıştırılabilir. Kapanan kaydın değişim, tamir, ret veya bertaraf sonucunu göstermesi stok ile zimmet verisinin aynı kalmasını sağlar.')
  'is-kiyafeti-kullanim-sonu-ayristirma-rehberi' = @('Ayırma kararının doğrulanması','Kullanım sonu değerlendirmesi yalnız görünüşe göre yapılmamalıdır. Ürün önce yeniden kullanım, profesyonel temizlik, onarım, parça geri kazanımı ve geri dönüşüm seçenekleri açısından sırayla incelenmelidir. Yağ, kimyasal veya biyolojik kirlenme şüphesi bulunan giysiler normal tekstil akışına verilmeden önce işletmenin atık ve iş güvenliği prosedürüne göre ayrılmalıdır. Ürün kodu, lif bileşimi, logo ve reflektif parça gibi ayrıştırmayı etkileyen bilgiler parti kaydına eklenebilir. Tartılan toplam miktar ile kabul edilen geri kazanım miktarı ayrı tutulursa sürecin gerçek verimi ölçülür. Tedarikçi veya geri dönüşüm kuruluşundan alınan teslim belgesi dönemsel rapora bağlanmalı; kişisel bilgi veya kurumsal arma taşıyan parçalar için güvenli imha şartı ayrıca tanımlanmalıdır. Sonuçlar sonraki ürünün malzeme ve tamir edilebilirlik kararına girdi sağlamalıdır.')
  'is-kiyafeti-pilot-giyim-testi' = @('Pilot testin başarı ölçütleri','Pilot başlamadan önce hangi sonucun kabul edileceği yazılmalıdır. Beden uyumu, hareket kısıtı, ısı konforu, cep erişimi, aksesuar arızası, logo dayanımı ve yıkama sonrası değişim için ayrı ölçütler belirlenebilir. Katılımcılar farklı görev, beden ve vardiyaları temsil etmeli; her kullanıcıya verilen numunenin ürün kodu ve revizyonu kaydedilmelidir. Test süresi günlük kullanımın yalnız ilk izlenimini değil en az birkaç bakım çevrimini görecek kadar uzun seçilmelidir. Bildirimler serbest yorumla birlikte ürün bölgesi ve önem derecesiyle sınıflandırılmalıdır. Birden fazla değişken aynı anda değiştirilirse hangi düzeltmenin sonucu etkilediği anlaşılamaz. Bu nedenle revizyonlar kontrollü ilerletilmeli, kapanış toplantısında kabul edilen ve ertelenen maddeler ayrı yazılmalıdır. Seri üretim onayı yalnız numune fotoğrafına değil bu kayıtların tamamına bağlanmalıdır.')
  'isi-yukunu-azaltan-is-kiyafeti-tasarimi' = @('Isı yükü denemesinde karşılaştırma yöntemi','Daha hafif kumaş tek başına daha düşük ısı yükü anlamına gelmez. Hava geçirgenliği, nem aktarımı, renk, katman sayısı, kalıp açıklığı ve kullanılan koruyucu ekipman birlikte değerlendirilmelidir. Pilot karşılaştırma benzer görev, vardiya saati ve ortam koşulunda yapılmalı; çalışanların mola ihtiyacı, ıslaklık hissi, hareket rahatlığı ve kuruma süresi aynı formda kaydedilmelidir. Ceplerin aşırı yüklenmesi ve havalandırma bölgelerinin başka ekipmanla kapanması tasarım avantajını azaltabilir. Koruyucu standart gereken işlerde havalandırma amacıyla yapılan açıklık veya malzeme değişikliği belge kapsamını bozabileceğinden üretici ve iş güvenliği uzmanı tarafından doğrulanmalıdır. Sıcaklıkla ilişkili sağlık belirtileri bir tekstil değerlendirmesi değildir; işletmenin sıcak çalışma prosedürü ve sağlık yaklaşımı önceliklidir. Giysi seçimi, mühendislik ve çalışma düzeni önlemlerini tamamlayan bir katman olarak ele alınmalıdır.')
  'kapsul-is-gardirobu-planlama' = @('Kapsül setin adet hesabı','Kapsül gardırop, az sayıda model seçmekten önce görevleri ortak kullanım senaryolarında birleştirmeyi gerektirir. Her görev için haftalık kullanım günü, yıkama dönüş süresi, mevsim, yedek ihtiyacı ve kirlenme sıklığı yazılmalıdır. Üst, alt ve dış katmanların renk ile kalıp uyumu kadar aynı bakım programında işlenebilmesi de operasyonu sadeleştirir. Adet hesabına çalışanın üzerindeki takım, yıkamadaki ürün ve acil yedek ayrı kalemler olarak eklenmelidir. Çok özel bir model yalnız küçük bir görev grubunda kullanılıyorsa stok ve tekrar sipariş etkisi ayrıca değerlendirilmelidir. Pilot dağıtım sonunda giyilmeyen parçalar, sık beden değişimleri ve eksik kalan katmanlar incelenerek set revize edilmelidir. Böylece sadeleşme çalışan ihtiyacını azaltmak yerine kullanılmayan varyantları ve gereksiz stok kodlarını azaltır.')
  'moduler-is-kiyafeti-sistemi' = @('Modüller arası uyumluluk matrisi','Modüler sistemde her parçanın diğer katmanlarla fiziksel ve operasyonel uyumu kaydedilmelidir. İç katman, orta katman, dış katman, pantolon ve aksesuarlar için beden eşleşmesi, hareket payı, kapama noktaları, görünürlük alanı ve logo konumu bir matriste karşılaştırılabilir. Fermuarla birleşen parçalar varsa diş, yön, uzunluk ve üretim revizyonu sabitlenmelidir. Bir katmanın yenilenmesi diğer parçanın koruyucu alanını kapatmamalı veya cep kullanımını engellememelidir. Pilot provada çalışanlar sistemi gerçek görev sırasına göre giyip çıkarmalı; yalnız tek parça rahatlığı değerlendirilmemelidir. Depoda modül kodlarının açıkça ayrılması, uyumsuz eski ve yeni revizyonların birlikte dağıtılmasını önler. Sistem başarısı parça sayısıyla değil, aynı temel setin farklı hava ve görev koşullarına kontrollü biçimde uyarlanabilmesiyle ölçülmelidir.')
  'polar-is-kiyafetlerinde-lif-dokulmesi-kontrolu' = @('Lif dökülmesi için karşılaştırmalı kontrol','Kontrol için numuneler aynı boyutta ve aynı bakım koşulunda hazırlanmalıdır. İlk kullanım, yıkama öncesi yüzey, belirlenen yıkama çevrimleri ve kurutma sonrası durum ayrı fotoğraflanabilir. Koyu ve açık renkli standart bir karşı yüzey üzerinde yapılan sürtme gözlemi, gevşek lifin görünmesini kolaylaştırır; ancak laboratuvar testi yerine geçmez. Kesim kenarı, dikiş çevresi, cep içi ve fermuar temas bölgeleri ayrı incelenmelidir. Fırçalama veya yüksek ısı gibi bakım uygulamaları sonucu değiştirebileceğinden kullanılan program kayda eklenmelidir. Üretim lotları arasında fark görülürse kumaş lotu ve numune kodu birlikte saklanmalıdır. Temiz oda veya hassas üretim gibi kontrollü ortamlarda kabul ölçütü işletmenin proses gereksinimiyle belirlenmeli; sıradan saha gözlemiyle uygunluk iddiası oluşturulmamalıdır.')
  'tamir-edilebilir-is-kiyafeti-tasarimi' = @('Onarım için tasarım kontrolü','Tamir edilebilirlik, hasar oluştuktan sonra değil model onayında değerlendirilmelidir. Fermuar, çıtçıt, cırt bant, diz paneli ve cep gibi yüksek aşınma parçalarına dikiş hattı sökülebilir biçimde erişilebilmelidir. Yedek aksesuarın kodu, rengi ve ölçüsü teknik föyde tutulmalı; kumaş yaması için aynı veya uyumlu lot seçeneği planlanmalıdır. Logo, reflektif şerit veya koruyucu katman bulunan bölgelerde onarımın ürün performansına etkisi ayrıca doğrulanmalıdır. Atölye kaydı hasar bölgesi, neden, işlem, kullanılan parça, tarih ve uygulayan kişiyi içermelidir. Aynı modelde tekrarlanan onarımlar tasarım zayıflığını gösterebilir; yalnız tamir sayısını artırmak çözüm değildir. Onarım maliyeti, bekleme süresi ve kalan kullanım ömrü birlikte değerlendirilerek tamir veya değiştirme eşiği belirlenmelidir.')
  'vardiya-dolabi-is-kiyafeti-standardi' = @('Dolap standardının saha kontrolü','Temiz ve kullanılmış giysilerin aynı gözde tutulmaması temel başlangıçtır. Dolap kapasitesi çalışan başına verilen ürün adedi, vardiya değişim sıklığı ve yıkama toplama düzenine göre hesaplanmalıdır. Islak ürünün kapalı dolapta beklemesini önleyecek havalandırma ve teslim noktası tanımlanmalı; kişisel eşya, kimyasal madde ve koruyucu giysi ayrımı işletme risklerine göre yapılmalıdır. Dolap veya göz numarası zimmet kaydıyla eşleştirilebilir, fakat gereksiz kişisel veri görünür alanda tutulmamalıdır. Haftalık kontrolde karışmış ürün, eksik etiket, nem, koku, hasar ve yetkisiz stok ayrı neden kodlarıyla kaydedilmelidir. Ortak kullanım ürünü varsa temizlenmiş ve kullanılmış statüsü fiziksel olarak ayırt edilmelidir. Standart, yalnız düzen fotoğrafıyla değil dağıtım ve toplama akışındaki hataların azalmasıyla doğrulanmalıdır.')
}
foreach ($slug in $sections.Keys) {
  $path = Join-Path $root "bilgi-merkezi\$slug\index.html"
  $html = [IO.File]::ReadAllText($path, [Text.Encoding]::UTF8)
  if ($html -match 'data-editorial-strengthening="20260809"') { continue }
  $heading = [Net.WebUtility]::HtmlEncode($sections[$slug][0])
  $body = [Net.WebUtility]::HtmlEncode($sections[$slug][1])
  $module = "<section data-editorial-strengthening=`"20260809`"><h2>$heading</h2><p>$body</p></section>"
  $html = $html.Replace('<section class="knowledge-seo-links"', ($module + '<section class="knowledge-seo-links"'))
  [IO.File]::WriteAllText($path, $html, $utf8)
}
$followUps = @{
  'is-kiyafeti-iade-lojistigi'='Aylık kapanışta açık iade kayıtları fiziksel bekleyen paketlerle sayılmalı; kayıt ile stok farkı bulunduğunda neden ve düzeltme sorumlusu ayrıca belirtilmelidir.'
  'kapsul-is-gardirobu-planlama'='Mevsim geçişinde kullanılmayan parçalar incelenerek bir sonraki dağıtımın adetleri güncellenmeli ve gerekçesi satın alma kaydına eklenmelidir.'
  'moduler-is-kiyafeti-sistemi'='Tedarikçi değiştiğinde yalnız renk değil birleşme ölçüleri, beden uyumu, bakım davranışı ve aksesuar uyumluluğu yeniden numunede doğrulanmalıdır. Sonuç, eski ve yeni revizyon kodlarıyla kayıt altına alınmalıdır.'
  'vardiya-dolabi-is-kiyafeti-standardi'='Kontrol sıklığı kullanım yoğunluğuna göre belirlenmeli; tekrar eden uygunsuzluklarda yalnız çalışan uyarısı değil alan kapasitesi ve toplama planı da gözden geçirilmelidir.'
}
foreach ($slug in $followUps.Keys) {
  $path = Join-Path $root "bilgi-merkezi\$slug\index.html"
  $html = [IO.File]::ReadAllText($path, [Text.Encoding]::UTF8)
  $paragraph = [Net.WebUtility]::HtmlEncode($followUps[$slug])
  $module = "<p data-editorial-followup=`"20260809`">$paragraph</p>"
  if ($html -match 'data-editorial-followup="20260809"') {
    $html = [regex]::Replace($html, '<p data-editorial-followup="20260809">.*?</p>', $module, 1)
  } else {
    $html = $html.Replace('<section class="knowledge-seo-links"', ($module + '<section class="knowledge-seo-links"'))
  }
  [IO.File]::WriteAllText($path, $html, $utf8)
}
"Strengthened $($sections.Count) focused articles."
